aemo/urls.py
from django.urls import path

from aemo import views

urlpatterns = [
    # Famille
    path('famille/list/', views.FamilleListView.as_view(), name='aemo-famille-list'),
    path('famille/attente/', views.FamilleListView.as_view(mode='attente'), name='aemo-famille-attente'),
    path('famille/add/', views.FamilleCreateView.as_view(), name='aemo-famille-add'),
    path('famille/<int:pk>/edit/', views.FamilleUpdateView.as_view(), name='aemo-famille-edit'),
    path('famille/<int:pk>/delete/', views.FamilleDeleteView.as_view(), name='aemo-famille-delete'),
    path('famille/archivable/list/', views.FamilleArchivableListe.as_view(), name='aemo-famille-archivable'),
    path('famille/<int:pk>/niveau/add/', views.NiveauCreateUpdateView.as_view(), name='famille-niveau-add'),
    path('famille/<int:pk>/niveau/<int:niv_pk>/edit/', views.NiveauCreateUpdateView.as_view(),
         name='famille-niveau-edit'
         ),
    path('famille/<int:pk>/niveau/<int:niv_pk>/delete/', views.NiveauDeleteView.as_view(),
         name='famille-niveau-delete'),

    # Prestations
    path('prestation/menu/', views.PrestationMenu.as_view(), name='aemo-prestation-menu'),
    path('prestation/recap_perso/', views.PrestationRecapPersoView.as_view(), name='aemo-prestation-recap-perso'),
    path('famille/<int:pk>/prestation/list/', views.PrestationListView.as_view(), name='aemo-prestation-famille-list'),
    path('famille/<int:pk>/prestation/add/', views.PrestationCreateView.as_view(), name='aemo-prestation-famille-add'),
    path('famille/<int:pk>/prestation/<int:obj_pk>/edit/', views.PrestationUpdateView.as_view(),
         name='aemo-prestation-edit'),
    path('famille/<int:pk>/prestation/<int:obj_pk>/delete/', views.PrestationDeleteView.as_view(),
         name='aemo-prestation-delete'),
    path('prestation_gen/list/', views.PrestationListView.as_view(), name='aemo-prestation-gen-list'),
    path('prestation_gen/add/', views.PrestationCreateView.as_view(), name='aemo-prestation-gen-add'),
    path('prestations/list/', views.AdminPrestationListView.as_view(), name='aemo-prestation-adminlist'),

    # Doc. à imprimer
    path('famille/<int:pk>/print-coord/', views.AnalyseDemandePDFView.as_view(),
         name='aemo-print-analyse-demande'),
    path('famille/<int:pk>/print-contrat/', views.ContratCollaborationPDFView.as_view(),
         name='aemo-print-contrat-collaboration'),
    path('famille/<int:pk>/print-info/', views.CoordonneesPDFView.as_view(),
         name='aemo-print-coord-famille'),
    path('famille/<int:pk>/print-journal', views.JournalPDFView.as_view(),
         name='aemo-print-journal'),
    path('famille/<int:pk>/bilan_3mois/', views.print_docx, {'docname': 'bilan_3mois'},
         name='print-bilan-3mois'),
    path('famille/<int:pk>/bilan_annee/', views.print_docx, {'docname': 'bilan_annee'},
         name='print-bilan-annee'),
    path('famille/<int:pk>/bilan_final/', views.print_docx, {'docname': 'bilan_final'},
         name='print-bilan-final'),
    path('famille/<int:pk>/projet_commun/', views.print_docx, {'docname': 'projet_commun'},
         name='print-projet-commun'),

    # Demande, suivi, agenda, suivis terminés
    path('famille/<int:pk>/demande/', views.DemandeView.as_view(), name='aemo-demande'),
    path('famille/<int:pk>/suivi/', views.AemoSuiviView.as_view(), name='aemo-famille-suivi'),
    path('famille/<int:pk>/agenda/', views.AgendaAemoSuiviView.as_view(), name='aemo-famille-agenda'),
    path('suivis_termines/', views.SuivisTerminesListView.as_view(), name='aemo-suivis-termines'),

    # Journal
    path('famille/<int:pk>/journal/list/', views.JournalListView.as_view(), name='aemo-journal-list'),
    path('famille/<int:pk>/journal/add/', views.JournalCreateView.as_view(), name='aemo-journal-add'),
    path('famille/<int:pk>/journal/<int:obj_pk>/edit/', views.JournalUpdateView.as_view(),
         name='aemo-journal-edit'),
    path('famille/<int:pk>/journal/<int:obj_pk>/delete/', views.JournalDeleteView.as_view(),
         name='aemo-journal-delete'),
]

ser/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('person/list/', views.PersonListView.as_view(), name='asap-person-list'),
    path('person/enveille/list/', views.PersonEnVeilleListView.as_view(), name='asap-person-veille'),
    path('person/add/', views.PersonCreateView.as_view(), name='asap-person-add'),
    path('person/<int:pk>/change/', views.PersonUpdateView.as_view(), name='asap-person-change'),
    path('person/<int:pk>/delete/', views.PersonDeleteView.as_view(), name='asap-person-delete'),

    path('person/<int:pk>/journal/', views.JournalListView.as_view(), name='asap-journal-list'),
    path('person/<int:pk>/journal/add/', views.JournalCreateView.as_view(), name='asap-journal-add'),
    path('person/<int:pk>/journal/<int:obj_pk>/edit/', views.JournalUpdateView.as_view(), name='asap-journal-change'),

    path('person/<int:pk>/upload/', views.DocumentUploadView.as_view(), name='person-doc-upload'),
    path('person/<int:pk>/doc/<int:doc_pk>/delete/', views.DocumentDeleteView.as_view(), name='person-doc-delete'),

    path('place/list/', views.PlaceListView.as_view(), name='asap-place-list'),
    path('place/add/', views.PlaceCreateView.as_view(), name='asap-place-add'),
    path('place/<int:pk>/change/', views.PlaceUpdateView.as_view(), name='asap-place-change'),
    path('place/<int:pk>/delete/', views.PlaceDeleteView.as_view(), name='asap-place-delete'),

    path('utilisateur/dal/', views.UtilisateurAsapAutocompleteView.as_view(), name='asap-utilisateur-autocomplete'),


    path('prestation/list/', views.PrestationListView.as_view(), name='asap-prestation-list'),
    path('prestation/add/', views.PrestationCreateView.as_view(), name='asap-prestation-add'),
    path('prestation/<int:pk>/change/', views.PrestationUpdateView.as_view(), name='asap-prestation-change'),
    path('prestation/extra/<str:action>/add/', views.PrestationExtraAddView.as_view(),
         name='asap-prestation-extra-add'),
    path('prestation/<int:pk>/delete/', views.PrestationDeleteView.as_view(), name='asap-prestation-delete'),
    path('tshm/create/', views.TshmCreateView.as_view(), name="asap-tshm-add"),
    path('tshm/<int:pk>/change/', views.TshmUpdateView.as_view(), name="asap-tshm-change"),
    path('tshm/list/', views.TshmListView.as_view(), name='asap-tshm-list'),

]

aemo/forms.py
from datetime import date

from django import forms
from django.db.models import Count, Q

from dal import autocomplete
from tinymce.widgets import TinyMCE

from aemo.models import (
    FamilleAemo, Intervention, PrestationAemo, JournalAemo, SuiviAemo
)
from carrefour.forms import (
    AgendaFormBase, BootstrapMixin, BSRadioSelect, CleanNpaLocaliteMixin, DateInput,
    PickDateWidget, PrestationFormBase, PickDateTimeWidget
)
from carrefour.models import Contact, LibellePrestation, NiveauInterv, Utilisateur
from common.choices import MotifsFinSuivi, REGIONS_CHOICES


class DemandeAemoForm(BootstrapMixin, forms.ModelForm):
    class Meta:
        model = SuiviAemo
        fields = (
            'ref_aemo_presents', 'pers_famille_presentes', 'autres_pers_presentes',
            'difficultes', 'aides', 'disponibilites', 'autres_contacts', 'remarque'
        )
        widgets = {
            'difficultes': TinyMCE,
            'aides': TinyMCE,
            'disponibilites': TinyMCE,
        }


class RegionFilterForm(forms.Form):
    region = forms.ChoiceField(label="Région", required=False)

    def __init__(self, user, **kwargs):
        self.user = user
        super().__init__(**kwargs)
        equipes = FamilleAemo.check_perm_view(user)
        regions = []
        if 'littoral' in equipes:
            regions.extend([(k, v) for k, v in REGIONS_CHOICES if k.startswith('litt')])
        if 'montagnes' in equipes:
            regions.extend([(k, v) for k, v in REGIONS_CHOICES if k.startswith('mont')])
        if self.user.has_perm('aemo.manage_littoral') or self.user.has_perm(
                'aemo.manage_montagnes'):
            regions.insert(0, ('mont', 'AEMO-Montagnes'))
            regions.insert(0, ('litt', 'AEMO-Littoral'))
        self.fields['region'].choices = [('0', 'Toutes')] + regions

    def filter(self, familles):
        region = self.cleaned_data['region']
        if region and region != '0':
            if region == 'litt':
                familles = familles.filter(region__startswith='litt')
            elif region == 'mont':
                familles = familles.filter(region__startswith='mont')
            else:
                familles = familles.filter(region=region)
        return familles


class FamilleFilterForm(RegionFilterForm):
    statut = forms.ChoiceField(label="Statut", required=False)
    interv = forms.ChoiceField(label="Intervenant-e", required=False)
    letter = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': 'Recherche…', 'autocomplete': 'off'}), required=False
    )

    def __init__(self, user, **kwargs):
        self.user = user
        super().__init__(user, **kwargs)
        self.fields['interv'].choices = [
            ('', 'Tous'), ('0', 'Aucun')] + [
            (user.id, user.nom_prenom) for user in user.utilisateurs_meme_equipe()
        ]
        self.fields['statut'].choices = [
            ('', 'Tous'),
            ('demande_prioritaire', 'Demande prioritaire'),
            ('demande_eventuelle', 'Demande éventuelle'),
        ] + [(key, etape.nom) for key, etape in SuiviAemo.WORKFLOW.items()]

    def filter(self, familles):
        if self.cleaned_data['interv']:
            if self.cleaned_data['interv'] == '0':
                familles = familles.annotate(
                    num_interv=Count('suiviaemo__intervention', filter=Q(suiviaemo__intervention__date_fin=None))
                ).filter(
                    num_interv=0
                )
            else:
                familles = familles.filter(
                    suiviaemo__aemo_referents=self.cleaned_data['interv'],
                    suiviaemo__intervention__date_fin=None
                )

        if self.cleaned_data['letter']:
            familles = familles.filter(nom__istartswith=self.cleaned_data['letter'])

        familles = super().filter(familles)

        if self.cleaned_data['statut']:
            if self.cleaned_data['statut'] == 'demande_prioritaire':
                familles = familles.filter(suiviaemo__demande_prioritaire=True)
            elif self.cleaned_data['statut'] == 'demande_eventuelle':
                familles = familles.filter(suiviaemo__date_demande_eventuelle__isnull=False,
                                           suiviaemo__date_demande__isnull=True)
            else:
                result = []
                for fam in familles:
                    if fam.suiviaemo.etape and fam.suiviaemo.etape.code == self.cleaned_data['statut']:
                        result.append(fam.pk)
                familles = FamilleAemo.objects.filter(pk__in=result)
        return familles


class SuiviAemoForm(BootstrapMixin, forms.ModelForm):
    ope_referent = forms.ModelChoiceField(
        queryset=Contact.membres_ope(), required=False, label='Interv. IPE'
    )
    referents_actifs = forms.ModelMultipleChoiceField(
        queryset=Utilisateur.objects.actifs(),
        required=False,
        label='Intervenant-e-s AEMO',
        widget=autocomplete.ModelSelect2Multiple(
            url='utilisateur-autocomplete',
            attrs={'title': "CTRL + clic pour sélectionner ou déselectionner un-e autre intervenant-e."}
        ),
    )

    class Meta:
        model = SuiviAemo
        fields = (
            'equipe', 'ope_referent', 'mandat_ope', 'referents_actifs', 'referent_note',
            'service_orienteur', 'motif_demande', 'detail_demande', 'demande_prioritaire', 'demarche', 'remarque',
            'remarque_privee'
        )
        labels = {
            'service_orienteur': 'Service orienteur',
            'referent_note': 'Autres intervenant-e-s',
            'remarque_privee': 'Remarque privée (non imprimée)',
            'demarche': 'Statut de la démarche',
        }

    def __init__(self, *args, **kwargs):
        kwargs['initial']['referents_actifs'] = kwargs['instance'].suivi_referents
        super().__init__(*args, **kwargs)

    def save(self, **kwargs):
        instance = super().save(**kwargs)
        if 'referents_actifs' in self.changed_data:
            added = [
                ref for ref in self.cleaned_data['referents_actifs']
                if ref not in self.initial['referents_actifs']
            ]
            for ref in added:
                Intervention.objects.create(suivi=instance, intervenant=ref, date_debut=date.today())
            deleted = [
                ref for ref in self.initial['referents_actifs']
                if ref not in self.cleaned_data['referents_actifs']
            ]
            for ref in deleted:
                inter = instance.intervention_set.get(intervenant=ref, date_fin=None)
                inter.date_fin = date.today()
                inter.save()
        return instance


class AgendaAemoForm(AgendaFormBase):
    ope_referent = forms.ModelChoiceField(
        queryset=Contact.membres_ope(), required=False
    )

    class Meta:
        model = SuiviAemo
        fields = (
            'date_demande_eventuelle', 'date_demande', 'date_analyse', 'date_confirmation',
            'date_debut_suivi', 'date_bilan_3mois', 'date_bilan_annee',
            'date_prolongation_1', 'date_bilan_prolongation_1',
            'date_prolongation_2', 'date_bilan_prolongation_2',
            'date_bilan_final', 'date_fin_suivi', 'motif_fin_suivi'
        )
        widgets = {field: PickDateWidget for field in fields[:-1]}

    def __init__(self, data=None, **kwargs):
        super().__init__(data=data, **kwargs)
        empty = [('', '--------')]
        has_suivi = self.instance.date_debut_suivi is not None or bool(data and data.get('date_debut_suivi'))
        self.fields['motif_fin_suivi'].choices = empty + (
            MotifsFinSuivi.choices_fin() if has_suivi else MotifsFinSuivi.choices_abandon('aemo')
        )

    def clean(self):
        cleaned_data = super().clean()
        original = SuiviAemo.objects.get(pk=self.instance.pk)
        errors = []
        if original.date_debut_suivi is None and cleaned_data.get('date_debut_suivi') is not None:
            # Coordonnées de la famille
            required_fields = ['npa', 'localite', 'rue', 'telephone', 'region']
            for field in required_fields:
                if getattr(original.famille, field) == '':
                    verbose = FamilleAemo._meta.get_field(field).verbose_name
                    errors.append(f"Famille: Le champ «{verbose}» est nécessaire pour continuer.")
            # Enfants suivis
            for enfant in original.famille.membres_suivis():
                if getattr(enfant, "date_naissance") in [None, '']:
                    errors.append(
                        f"{enfant.nom_prenom}: Le champ «Date de naissance» est nécessaire pour continuer.")
                if getattr(enfant.formation, "statut") in [None, '']:
                    errors.append(
                        f"{enfant.nom_prenom}: Le champ «Scolarité (cycle)» est nécessaire pour continuer.")
            # Suivi
            required_fields = ['mandat_ope', 'motif_demande', 'demarche']
            for field in required_fields:
                if getattr(original, field) in [None, '']:
                    verbose = SuiviAemo._meta.get_field(field).verbose_name
                    errors.append(f"Suivi: Le champ «{verbose}» est nécessaire pour continuer.")
        if errors:
            raise forms.ValidationError(errors)
        return self.cleaned_data


class PrestationAemoForm(PrestationFormBase):

    class Meta(PrestationFormBase.Meta):
        model = PrestationAemo
        fields = ('lib_prestation', 'date_prestation', 'duree')

    def __init__(self, *args, famille=None, prest_codes=None, user=None, **kwargs):
        self.famille = famille
        super().__init__(*args, user=user, **kwargs)
        self.fields['lib_prestation'] = forms.ModelChoiceField(
            label='Prestations',
            queryset=LibellePrestation.objects.filter(unite='aemo', code__in=prest_codes).order_by('code'),
            widget=BSRadioSelect,

templates/aemo/demande_edit.html
{% extends "base.html" %}

{% block boutons_droite %}
    {% if form.instance.pk %}
        {% include source|add:'/famille_boutons.html' with active='demande' %}
    {% endif %}
{% endblock %}

{% block content %}
    <div class="row border-bottom mb-5">
        <div class="col lead">Famille {{ famille.nom }} - {{ famille.adresse }}</div>
        <div class="col text-end lead">Analyse de la demande</div>
    </div>
    <div class="row justify-content-center mb-3">
        <div class="col-10">
            <form action= "." name="DemandeForm" method="post">{% csrf_token %}
                <input type="hidden" name="famille" value="{{ famille.pk }}">
                <table class="table table-sm table-borderless">
                    {{ form.as_table }}
                    <tr>
                        <th>Réseau prof.</th>
                        <td>
                            <table>
                                <tr>
                                    <td>Famille:</td>
                                    <td>{{ famille.suivi.get_ope_referents }}</td>
                                </tr>
                                {% for enfant in famille.membres_suivis %}
                                    {% for ct in enfant.reseaux.all %}
                                        <tr>
                                            <td>{{ enfant.prenom }}:</td>
                                            <td>{{ ct }} {{ ct.contact }}</td>
                                        </tr>
                                    {% endfor %}
                                {% endfor %}
                            </table>
                        </td>
                    </tr>
                </table>
                {% if famille|can_edit:user %}
                    {% include "actions.html" %}
                {% endif %}
            </form>
        </div>
    </div>

{% endblock %}

templates/aemo/famille_boutons.html
<a class="btn btn-outline-primary btn-sm {% if active == 'coordonnees' %} active {% endif %}" href="{% url 'aemo-famille-edit' famille.pk %}">Coordonnées</a>
<a class="btn btn-outline-primary btn-sm {% if active == 'demande' %} active {% endif %}" href="{% url 'aemo-demande' famille.pk %}">Demande</a>
<a class="btn btn-outline-primary btn-sm {% if active == 'journal' %} active {% endif %}" href="{% url 'aemo-journal-list' famille.pk %}">Journal</a>
<a class="btn btn-outline-primary btn-sm {% if active == 'suivi' %} active {% endif %}" href="{% url 'aemo-famille-suivi' famille.pk %}">Suivi</a>
<a class="btn btn-outline-primary btn-sm {% if active == 'agenda' %} active {% endif %}"
   href="{% url 'aemo-famille-agenda' famille.pk %}">Agenda</a>
<a class="btn btn-outline-primary btn-sm {% if active == 'prestation' %} active {% endif %}" href="{% url 'aemo-prestation-famille-list' famille.pk %}">Prestations</a>

templates/aemo/famille_list.html
{% extends "base.html" %}

{% block extra_javascript %}
<script type="text/javascript">
    $(document).ready(function() {
        $("#id_statut, #id_interv, #id_region").change(function() { this.form.submit(); });
    });
</script>
{% endblock %}

{% block boutons_droite %}
<div class="topnav-right">
    <form class="inline" method="get" action=".">
        <div class="select-container">
            {{ form.region.label_tag }} {{ form.region }}
        </div>
        {% if form.interv %}
        <div class="select-container">
            {{ form.interv.label_tag }} {{ form.interv }}
        </div>
        <div class="select-container">
            {{ form.statut.label_tag }} {{ form.statut }}
        </div>
        <div class="select-container">
            {{ form.letter }}
            <button id="search-button" type="submit"><img src="{% static 'admin/img/search.svg' %}"></button>
        </div>
        {% endif %}
    </form>
</div>
{% endblock %}

{% block content %}
    <div class="row border-bottom mb-3">
        <div class="col lead">Familles {{ equipe_value }} <span class="fs-6">({{ tot_familles }} familles)</span> </div>
        <div class="col text-end">
            {% if view.mode == 'attente' %}
                <a class="btn btn-sm btn-outline-primary" href="{% url 'aemo-famille-list' %}">Liste</a>
            {% else %}
                <a class="btn btn-sm btn-outline-primary" href="{% url 'aemo-famille-attente' %}">Liste d'attente</a>
            {% endif %}
            {% if perms.aemo.change_littoral or perms.aemo.change_montagnes %}
                <a class="btn btn-sm btn-outline-primary" href="{% url 'aemo-famille-add' %}">Nouvelle famille</a>
            {% endif %}
        </div>
    </div>
    <div class="row">
        <div class="col">
            <table id="benef_table" class="table table-sm table-hover sortable">
                <thead class="table-light">
                    <tr>
                    {% for label in labels %}
                        <th>{{ label }}</th>
                    {% endfor %}
                    </tr>
                </thead>
                <tbody>
                    {% for famille in object_list %}
                        <tr data-statut="{{ famille.suiviaemo.etape.code }}" data-intervenant="{{ famille.suiviaemo|referents_pk_data }}">
                            {% for col_key in col_keys %}
                            {% if col_key == 'nom' %}
                            <td class="m-0 p-0">
                                <div>
                                    <a href="{% url 'aemo-famille-suivi' famille.id %}" title="Suivi">{{ famille.nom }}</a>
                                    <span class="hoverimage">
                                        <a class="btn btn-sm m-0 p-0" role="button"
                                           href="{% url 'aemo-famille-edit' famille.pk %}"
                                           title="{{ famille.telephone }}">
                                            <img src="{% static 'img/coordonnees.gif' %}" width="15px" height="15px">
                                        </a>
                                    </span>
                                </div></td>
                            {% elif col_key == 'localite' %}
                            <td class="m-0 p-0">{{ famille.npa}} {{ famille.localite }}</td>
                            {% elif col_key == 'referents' %}
                            <td class="m-0 p-0">{{ famille.suiviaemo|sigles_referents }}</td>
                            {% elif col_key == 'referents_ope' %}
                            <td class="m-0 p-0">
                                {{ famille.suiviaemo.ope_referent|info_ope }}
                            </td>
                            {% elif col_key == 'suivi' %}
                            <td class="m-0 p-0" data-sort="{{ famille.suiviaemo.etape.num }}">
                                <table class="statut_suivi">
                                    <tr><td>{{ famille.suiviaemo|etape_cellule:"demande" }}</td>
                                        <td>{{ famille.suiviaemo|etape_cellule:"analyse" }}</td>
                                        <td>{{ famille.suiviaemo|etape_cellule:"confirmation" }}</td>
                                        <td>{{ famille.suiviaemo|etape_cellule:"debut_suivi" }}</td>
                                        <td>{{ famille.suiviaemo|etape_cellule:"bilan_3mois" }}</td>
                                        <td>{{ famille.suiviaemo|etape_cellule:"bilan_annee" }}</td>
                                        <td>{{ famille.suiviaemo|etape_cellule:"prolongation_1" }}</td>
                                        <td>{{ famille.suiviaemo|etape_cellule:"bilan_prolongation_1" }}</td>
                                        <td>{{ famille.suiviaemo|etape_cellule:"prolongation_2" }}</td>
                                        <td>{{ famille.suiviaemo|etape_cellule:"bilan_final" }}</td>
                                        <td>{{ famille.suiviaemo|etape_cellule:"fin_suivi" }}</td>
                                    </tr>
                                </table>
                            </td>
                            {% elif col_key == 'prioritaire' %}
                            <td class="m-0 px-1 py-0">{{ famille.suiviaemo.demande_prioritaire|yesno:'Oui,' }}</td>
                            {% elif col_key == 'niveau_interv' %}
                            <td class="text-center">{{ famille.niveau_actuel|default_if_none:'-' }}</td>
                            {% elif col_key == 'date_demande' %}
                            <td class="m-0 px-1 py-0" data-sort="{{ famille.suiviaemo.date_demande|date:'Ymd' }}">
                                {{ famille.suiviaemo.date_demande|date:"d.m.Y" }}
                            </td>
                            <td class="m-0 px-1 py-0" data-sort="{{ famille.suiviaemo.date_analyse|date:'Ymd' }}">
                                {{ famille.suiviaemo.date_analyse|date:"d.m.Y" }}
                            </td>
                            {% elif col_key == 'date_confirmation' %}
                            <td class="m-0 px-1 py-0" data-sort="{{ famille.suiviaemo.date_confirmation|date:'Ymd' }}">
                                {{ famille.suiviaemo.date_confirmation|date:"d.m.Y" }}
                            </td>
                            {% elif col_key == 'region' %}
                            <td class="m-0 px-1 py-0">{{ famille.get_region_display }}</td>
                            {% endif %}
                        {% endfor %}
                        </tr>
                    {% empty %}
                        <tr>
                            <td colspan="8" class="bg-warning" align="center">
                                <i>Aucune famille ne correspond à votre recherche.</i>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

templates/aemo/journal_edit.html
{% extends "base.html" %}

{% block boutons_droite %}
    {% include source|add:'/famille_boutons.html' with active='journal' %}
{% endblock %}

{% block content %}
    <div class="row border-bottom lead mb-5">
        <div class="col lead">Famille {{ famille.nom }} - {{ famille.adresse }}</div>
        <div class="col text-end lead">Journal d'interventions</div>
    </div>

    <div class="row justify-content-center">
        <div class="col-8">
            <form name="JournalForm" action="." method="post">{% csrf_token %}
                <table class="table table-sm">
                    {{ form.as_table }}
                </table>
                {% include "actions.html" %}
            </form>
        </div>
    </div>
{% endblock %}

templates/aemo/prestation_edit.html
{% extends "base.html" %}

{% block boutons_droite %}
    {% if famille %}
        {% include source|add:'/famille_boutons.html' with active='prestation' %}
    {% endif %}
{% endblock %}

{% block content %}
    <div class="row border-bottom mb-3">
        <div class="col lead">
            {% if famille %}
                Famille {{ famille.nom }} - {{ famille.adresse  }}
            {% else %}
                Mes prestations générales
            {% endif %}
        </div>
    </div>

    <div class="row mb-5 justify-content-center">
        <div class="col-6">
            <form action="#" method="post">{% csrf_token %}
                <table class="table table-sm table-borderless">
                    <tr>
                        <td width="40%"></td><td></td>
                    </tr>
                    {{ form.as_table }}
                </table>
                {% include "actions.html" %}
            </form>
        </div>
    </div>

    <div class="row mt-4 justify-content-center" style="font-size:90%;">
        {% for prestation in form.lib_prestation.field.queryset.all %}
            <div class="col-3">
                <h6>{{ prestation.nom }}</h6>
                <ul>
                    {% for acte in prestation.actes_aprester.all %}
                       <li>{{ acte.nom }}</li>
                    {% endfor %}
                </ul>
            </div>
        {% endfor %}
    </div>
{% endblock %}