carrefour/urls.py
from django.urls import path
from carrefour import views

urlpatterns = [
    path('contact/add/', views.ContactCreateView.as_view(), name='contact-add'),
    path('contact/list/', views.ContactListView.as_view(), name='contact-list'),
    path('contact/<int:pk>/edit/', views.ContactUpdateView.as_view(), name='contact-edit'),
    path('contact/<int:pk>/delete/', views.ContactDeleteView.as_view(), name='contact-delete'),
    path('contact/dal/', views.ContactAutocompleteView.as_view(), name='contact-autocomplete'),
    path('contact/dal-ope/', views.ContactAutocompleteView.as_view(ope=True),
         name='contact-ope-autocomplete'),
    path('contact/dal-externe/', views.ContactExterneAutocompleteView.as_view(),
         name='contact-externe-autocomplete'),
    path('contact/test/doublon/', views.ContactTestDoublon.as_view(), name='contact-doublon'),
    path('contact/<int:pk>/dossier/list/', views.ContactDossiersActifsView.as_view(), name='contact-dossier'),
    path('contact/<int:pk>/merge/', views.ContactMergeView.as_view(), name='contact-merge'),

    path('service/add/', views.ServiceCreateView.as_view(), name='service-add'),
    path('service/list/', views.ServiceListView.as_view(), name='service-list'),
    path('service/<int:pk>/edit/', views.ServiceUpdateView.as_view(), name='service-edit'),
    path('service/<int:pk>/delete/', views.ServiceDeleteView.as_view(), name='service-delete'),

    # Personne
    path('<slug:source>/famille/<int:pk>/personne/add/', views.PersonneCreateView.as_view(), name="personne-add"),
    path('<slug:source>/famille/<int:pk>/personne/<int:obj_pk>/edit/', views.PersonneUpdateView.as_view(),
         name="personne-edit"),
    path('<slug:source>/famille/<int:pk>/personne/<int:obj_pk>/delete/', views.PersonneDeleteView.as_view(),
         name='personne-delete'),

    path('personne/<int:pk>/formation/', views.FormationView.as_view(), name='formation'),
    path('personne/<int:pk>/contacts/', views.PersonneReseauListView.as_view(), name='personne-reseau-list'),
    path('personne/<int:pk>/contact/add/', views.PersonneReseauAddView.as_view(), name='personne-reseau-add'),
    path('personne/<int:pk>/contact/<int:obj_pk>/remove/', views.PersonneReseauRemove.as_view(),
         name='personne-reseau-remove'),
    path('personne/<int:pk>/toggle_contract/', views.PersonneToggleContract.as_view(),
         name='personne-toggle-contract'),
    path('famille/<int:pk>/upload/', views.DocumentUploadView.as_view(), name='famille-doc-upload'),
    path('famille/<int:pk>/genogramme/upload/', views.GenogrammeUploadView.as_view(),
         name='famille-genogramme-upload'),
    path('famille/<int:pk>/sociogramme/upload/', views.SociogrammeUploadView.as_view(),
         name='famille-sociogramme-upload'),
    path('famille/<int:pk>/genogramme/delete/', views.FamilleFileDeleteView.as_view(field_name='genogramme'),
         name='famille-genogramme-delete'),
    path('famille/<int:pk>/sociogramme/delete/', views.FamilleFileDeleteView.as_view(field_name='sociogramme'),
         name='famille-sociogramme-delete'),

    path('famille/<int:pk>/doc/<int:doc_pk>/delete/', views.DocumentDeleteView.as_view(), name='famille-doc-delete'),

    path('utilisateur/', views.UtilisateurListView.as_view(), name='utilisateur-list'),
    path('utilisateur/<int:pk>/edit/', views.UtilisateurUpdateView.as_view(), name='utilisateur-edit'),
    path('utilisateur/add/', views.UtilisateurCreateView.as_view(), name='utilisateur-add'),
    path('utilisateur/<int:pk>/delete/', views.UtilisateurDeleteView.as_view(), name='utilisateur-delete'),
    path('utilisateur/<int:pk>/password_reinit/', views.UtilisateurPasswordReinitView.as_view(),
         name='utilisateur-password-reinit'),
    path('utilisateur/dal/', views.UtilisateurAutocompleteView.as_view(), name='utilisateur-autocomplete'),
    path('utilisateur/<int:pk>/otp_device/reinit/', views.UtilisateurOtpDeviceReinitView.as_view(),
         name='utilisateur-otp-device-reinit'),
    path('utilisateur/desactive/list/', views.UtilisateurListView.as_view(is_active=False),
         name='utilisateur-desactive-list'),
    path('utilisateur/<int:pk>/reactiver/', views.UtilisateurReactivateView.as_view(),
         name='utilisateur-reactiver'),

    path('utilisateur/<int:pk>/derogation/add/', views.DerogationSaisieTardiveCreateView.as_view(),
         name='utilisateur-derogation-add'),
    path('utilisateur/<int:pk>/derogation/<int:obj_pk>/edit/', views.DerogationSaisieTardiveUpdateView.as_view(),
         name='utilisateur-derogation-edit'),


    path('cerclescolaire/', views.CercleScolaireListView.as_view(), name='cercle-list'),
    path('cerclescolaire/<int:pk>/edit/', views.CercleScolaireUpdateView.as_view(), name='cercle-edit'),
    path('cerclescolaire/add/', views.CercleScolaireCreateView.as_view(), name='cercle-add'),
    path('cerclescolaire/<int:pk>/delete/', views.CercleScolaireDeleteView.as_view(), name='cercle-delete'),

    path('role/', views.RoleListView.as_view(), name='role-list'),
    path('role/<int:pk>/edit/', views.RoleUpdateView.as_view(), name='role-edit'),
    path('role/add/', views.RoleCreateView.as_view(), name='role-add'),
    path('role/<int:pk>/delete/', views.RoleDeleteView.as_view(), name='role-delete'),

    path('permissions/', views.PermissionOverview.as_view(), name='permissions'),

    path('export/prestation/', views.ExportPrestationView.as_view(), name='export-prestation'),
]

ser/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('person/list/', views.PersonListView.as_view(), name='asap-person-list'),
    path('person/enveille/list/', views.PersonEnVeilleListView.as_view(), name='asap-person-veille'),
    path('person/add/', views.PersonCreateView.as_view(), name='asap-person-add'),
    path('person/<int:pk>/change/', views.PersonUpdateView.as_view(), name='asap-person-change'),
    path('person/<int:pk>/delete/', views.PersonDeleteView.as_view(), name='asap-person-delete'),

    path('person/<int:pk>/journal/', views.JournalListView.as_view(), name='asap-journal-list'),
    path('person/<int:pk>/journal/add/', views.JournalCreateView.as_view(), name='asap-journal-add'),
    path('person/<int:pk>/journal/<int:obj_pk>/edit/', views.JournalUpdateView.as_view(), name='asap-journal-change'),

    path('person/<int:pk>/upload/', views.DocumentUploadView.as_view(), name='person-doc-upload'),
    path('person/<int:pk>/doc/<int:doc_pk>/delete/', views.DocumentDeleteView.as_view(), name='person-doc-delete'),

    path('place/list/', views.PlaceListView.as_view(), name='asap-place-list'),
    path('place/add/', views.PlaceCreateView.as_view(), name='asap-place-add'),
    path('place/<int:pk>/change/', views.PlaceUpdateView.as_view(), name='asap-place-change'),
    path('place/<int:pk>/delete/', views.PlaceDeleteView.as_view(), name='asap-place-delete'),

    path('utilisateur/dal/', views.UtilisateurAsapAutocompleteView.as_view(), name='asap-utilisateur-autocomplete'),


    path('prestation/list/', views.PrestationListView.as_view(), name='asap-prestation-list'),
    path('prestation/add/', views.PrestationCreateView.as_view(), name='asap-prestation-add'),
    path('prestation/<int:pk>/change/', views.PrestationUpdateView.as_view(), name='asap-prestation-change'),
    path('prestation/extra/<str:action>/add/', views.PrestationExtraAddView.as_view(),
         name='asap-prestation-extra-add'),
    path('prestation/<int:pk>/delete/', views.PrestationDeleteView.as_view(), name='asap-prestation-delete'),
    path('tshm/create/', views.TshmCreateView.as_view(), name="asap-tshm-add"),
    path('tshm/<int:pk>/change/', views.TshmUpdateView.as_view(), name="asap-tshm-change"),
    path('tshm/list/', views.TshmListView.as_view(), name='asap-tshm-list'),

]

carrefour/models.py
import os
from datetime import date, timedelta
from django.conf import settings
from django.contrib.auth.models import AbstractUser, UserManager
from django.contrib.postgres.fields import DateRangeField
from django.core.exceptions import ObjectDoesNotExist
from django.core.validators import FileExtensionValidator, MaxValueValidator
from django.db import models, transaction
from django.db.models import Count, F, OuterRef, Q, Subquery, Sum, Value
from django.db.models.functions import Coalesce, ExtractMonth, ExtractYear, NullIf
from django.db.utils import IntegrityError
from django.urls import reverse
from django.utils import timezone

from common import choices

from .utils import format_adresse, format_contact, format_duree, format_d_m_Y, random_string_generator


class CercleScolaire(models.Model):
    """ Les 7 cercles scolaires du canton"""

    nom = models.CharField(max_length=50, unique=True)
    telephone = models.CharField('tél.', max_length=35, blank=True)

    class Meta:
        verbose_name = 'Cercle scolaire'
        verbose_name_plural = 'Cercles scolaires'
        ordering = ('nom',)

    def __str__(self):
        return self.nom


class Service(models.Model):
    """ Tous les services sociaux en lien avec AEMO"""

    sigle = models.CharField('Sigle', max_length=10, unique=True)
    nom_complet = models.CharField('Nom complet', max_length=80, blank=True)

    class Meta:
        ordering = ('sigle',)

    def __str__(self):
        return self.sigle

    def save(self, *args, **kwargs):
        self.sigle = self.sigle.upper()
        super().save(*args, **kwargs)


class RoleManager(models.Manager):
    def get_by_natural_key(self, nom):
        return self.get(nom=nom)


class Role(models.Model):
    NON_EDITABLE = ['Père', 'Mère', 'Enfant suivi', 'Enfant non-suivi']

    nom = models.CharField("Nom", max_length=50, unique=True)
    famille = models.BooleanField("Famille", default=False)

    objects = RoleManager()

    class Meta:
        ordering = ('nom',)

    def __str__(self):
        return self.nom

    @property
    def editable(self):
        return self.nom not in self.NON_EDITABLE

    def natural_key(self):
        return (self.nom,)


class Contact(models.Model):
    prenom = models.CharField('Prénom', max_length=30)
    nom = models.CharField('Nom', max_length=30)
    rue = models.CharField('Rue', max_length=30, blank=True)
    npa = models.CharField('NPA', max_length=4, blank=True)
    localite = models.CharField('Localité', max_length=30, blank=True)
    telephone = models.CharField('Tél.', max_length=30, blank=True)
    email = models.EmailField('Courriel', max_length=100, blank=True)
    service = models.ForeignKey(Service, null=True, blank=True, on_delete=models.PROTECT)
    role = models.ForeignKey(Role, null=True, blank=True, on_delete=models.PROTECT, verbose_name="Rôle")
    profession = models.CharField('Activité/prof.', max_length=100, blank=True)
    remarque = models.TextField("Remarque", blank=True)
    est_actif = models.BooleanField('actif', default=True)

    class Meta:
        verbose_name = 'Contact'
        ordering = ('nom', 'prenom')
        constraints = [
            models.UniqueConstraint(
                fields=['nom', 'prenom', 'service'], condition=Q(est_actif=True), name='unique_contact'
            )
        ]

    def __str__(self):
        sigle = self.service.sigle if self.service else ''
        return '{} ({})'.format(self.nom_prenom, sigle) if self.service else self.nom_prenom

    @property
    def nom_prenom(self):
        return '{} {}'.format(self.nom, self.prenom)

    @property
    def nom_initiale_prenom(self):
        return f"{self.prenom[0]}. {self.nom}"

    @property
    def adresse(self):
        return format_adresse(self.rue, self.npa, self.localite)

    @property
    def contact(self):
        return format_contact(self.telephone, self.email)

    @classmethod
    def membres_ope(cls):
        return cls.objects.filter(service__sigle__startswith='OPE', est_actif=True)

    def dossiers(self, actif=True):
        filtre = {'date_sortie__isnull': True} if actif else {}
        batoude = [f"{benef.nom} {benef.prenom} (Batoude)" for benef in
                   self.beneficiaire_set.filter(**filtre)]
        batoude.extend([f"{benef.nom} {benef.prenom} (Batoude)" for benef in
                        self.suivisbatoude.filter(**filtre)])
        batoude.extend([f"{benef.nom} {benef.prenom} (Batoude)" for benef in
                        self.suivisbatoude2.filter(**filtre)])
        filtre = {'famille__suiviaemo__id__isnull': False}
        if actif:
            filtre['famille__suiviaemo__date_fin_suivi__isnull'] = True
        aemo = [f"Fam. {pers.famille.nom} (Aemo)" for pers in self.personne_set.filter(**filtre)]
        filtre = {'date_fin_suivi__isnull': True} if actif else {}
        aemo.extend([f"Fam. {suivi.famille.nom} (Aemo)" for suivi in
                     self.suivisaemo.filter(**filtre)])
        filtre = {'famille__suiviasaef__id__isnull': False}
        if actif:
            filtre['famille__suiviasaef__date_fin_suivi__isnull'] = True
        asaef = [f"Fam. {pers.famille.nom} (Asaef)" for pers in self.personne_set.filter(**filtre)]
        filtre = {'date_fin_suivi__isnull': True} if actif else {}
        asaef.extend([f"Fam. {suivi.famille.nom} (Asaef)" for suivi in
                      self.suivisasaef.filter(**filtre)])
        filtre = {'statut': 'actif'} if actif else {}
        asap = [f"{pers.nom} {pers.prenom} (Asap)" for pers in self.beneficiaires.filter(**filtre)]
        return aemo + asaef + batoude + asap

    def fusionner(self, *doublons):
        """
        Reporte les liens des doublons sur le contact courant
        puis supprime les doublons.
        """
        with transaction.atomic():
            for doublon in doublons:
                # Batoude
                for benef in doublon.beneficiaire_set.all():
                    benef.reseau.add(self)
                    benef.reseau.remove(doublon)
                # Aemo - Asaef
                for person in doublon.personne_set.all():
                    person.reseaux.add(self)
                    person.reseaux.remove(doublon)
                # Ser
                for benef in doublon.beneficiaires.all():
                    benef.contacts.add(self)
                    benef.contacts.remove(doublon)
                doublon.suivisaemo.update(ope_referent=self)
                doublon.suivisasaef.update(ope_referent=self)
                doublon.suivisasaef2.update(ope_referent2=self)
                doublon.suivisbatoude.update(referent_ope=self)
                doublon.suivisbatoude2.update(referent_ope2=self)

                doublon.delete()


class UtilisateurManager(UserManager):
    def actifs(self):
        return self.filter(date_desactivation__isnull=True, is_superuser=False)


class Utilisateur(Contact, AbstractUser):
    sigle = models.CharField(max_length=5, blank=True)
    date_desactivation = models.DateField('Date désactivation', null=True, blank=True)
    taux_activite = models.PositiveSmallIntegerField(
        "Taux d’activité (en %)", blank=True, default=0, validators=[MaxValueValidator(100)]
    )

    objects = UtilisateurManager()

    @property
    def groupes(self):
        return [item.name for item in self.groups.all()]

    def prestations(self, unite):
        """Renvoie toutes les prestations (liées ou générales) de l’utilisateur."""
        return getattr(self, f'prestations_{unite}').all()

    def prestations_gen(self, unite):
        """Renvoie les prestations générales de l’utilisateur."""
        if unite == 'batoude':
            return self.prestations_batoude.filter(beneficiaire__isnull=True)
        else:
            return self.prestations(unite).filter(famille__isnull=True)

    def temps_total_prestations(self, unite):
        return self.prestations(unite).model.temps_total(self.prestations(unite), tous_utilisateurs=False)

    def total_mensuel(self, unite, month, year):
        prestations = self.prestations(unite).filter(
            date_prestation__year=year, date_prestation__month=month
        )
        return self.prestations(unite).model.temps_total(prestations, tous_utilisateurs=False)

    def totaux_mensuels(self, unite, year):
        return [self.total_mensuel(unite, m, year) for m in range(1, 13)]

    def total_annuel(self, unite, year):
        prestations = self.prestations(unite).filter(date_prestation__year=year)
        return self.prestations(unite).model.temps_total(prestations, tous_utilisateurs=False)

    def utilisateurs_meme_equipe(self):
        equipes = [g.name for g in self.groups.all()]
        return Utilisateur.objects.filter(
            is_active=True, groups__name__in=equipes
        ).exclude(groups__name='direction').distinct()

    @classmethod
    def _intervenants(cls, groupes=(), annee=None):
        if annee is None:
            utils = Utilisateur.objects.actifs()
        else:
            utils = Utilisateur.objects.filter(
                Q(is_superuser=False) & (
                    Q(date_desactivation__isnull=True) | Q(date_desactivation__year=annee)
                )
            )
        return utils.filter(
            groups__name__in=groupes,
        ).exclude(
            groups__name__in=['direction']
        )

    @classmethod
    def intervenants_aemo(cls, annee=None):
        return cls._intervenants(groupes=['aemo_littoral', 'aemo_montagnes'], annee=annee).distinct()

    @classmethod
    def intervenants_asaef(cls, annee=None):
        return cls._intervenants(groupes=['asaef'], annee=annee)

    @classmethod
    def intervenants_batoude(cls, annee=None):
        return cls._intervenants(groupes=['batoude'], annee=annee)

    @classmethod
    def intervenants_asap(cls, annee=None):
        return cls._intervenants(groupes=['asap'], annee=annee)

    def heures_act_mens(self):

templates/carrefour/cercle_scolaire_edit.html
{% extends "base.html" %}

{% block content %}
    <div class="row border-bottom mb-5">
        <div class="col lead">Centre scolaire</div>
    </div>
    <div class="row justify-content-center">
        <div class="col-6">
            <form action="#" method="post">
                {% csrf_token %}
                <table class="table table-sm table-borderless">
                    {{ form.as_table }}
                </table>
                {% include "actions.html" %}
            </form>
        </div>
    </div>
{% endblock %}

templates/carrefour/cercle_scolaire_list.html
{% extends "base.html" %}

{% block content %}
    <div class="row border-bottom mb-3">
        <div class="col"><p class="lead">Centres scolaires</p></div>
        {% if perms.carrefour.add_cerclescolaire %}
        <div class="col text-end">
            <a class="btn btn-sm btn-outline-primary" href="{% url 'cercle-add' %}">Nouveau</a>
        </div>
        {% endif %}
    </div>
    <div class="row">
        <div class="col">
            <table id="list_ecole" class="table table-sm table-hover">
                <thead class="table-light">
                    <tr>
                        <th>Nom</th>
                        <th>Téléphone</th>
                    </tr>
                </thead>
                <tbody>
                    {% with can_edit=perms.carrefour.change_cerclescolaire %}
                    {% for item in object_list %}
                    <tr>
                        <td>{% if can_edit %}<a href="{% url 'cercle-edit' item.pk %}">{% endif %}{{ item.nom }}{% if can_edit %}</a>{% endif %}</td>
                        <td>{{ item.telephone }}</td>
                    </tr>
                    {% endfor %}
                    {% endwith %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

templates/carrefour/contact_list.html
{% extends "base.html" %}

{% block extra_javascript %}
<script>
$(document).ready(function() {
   $(".js-dossier-contact").click(function() {
      $.get($(this).data('url'), function(data) {
         $('#dossierContactModalLabel').html('Dossiers en cours de ' + data.contact);
         $('#dossierContactModal .modal-body').empty();
         $.each(data.dossiers, function(index, value) {
            $('#dossierContactModal .modal-body').append('<p>' + value + '</p>');
         });
      });
   });
});
</script>
{% endblock %}

{% block boutons_droite %}
    <div class="col text-end" style="font-size:90%;">
        {% if perms.carrefour.add_contact %}
            <div class="col text-end">
                <a class="btn btn-sm btn-outline-primary" href="{% url 'contact-add' %}">Nouveau contact</a>
            </div>
        {% endif %}
    </div>
{% endblock %}

{% block content %}
    <div class="row border-bottom mb-3">
        <div class="col"><p class="lead">Contacts Fondation Carrefour</p></div>
        {% include 'letter_choice.html' %}
    </div>
    <form method="get" action=".">
    <div class="row">
        <div class="col">
            <table id="contact_table" class="table table-sm table-hover sortable">
                <thead class="table-light">
                <tr>
                    {% if perms.carrefour.delete_contact %}
                    <th>Fusion
                        <button type="button" class="btn btn-warning btn-round"
                                data-bs-toggle="tooltip"
                                data-bs-placement="top"
                                title="Sélectionner deux ou plusieurs contacts. Seul le premier de la liste sera conservé et les données des suivants transférées.">i
                        </button>
                     </th>
                    {% endif %}
                    <th>Nom, prénom</th>
                    <th>Téléphone</th>
                    <th>Courriel</th>
                    <th>Service</th>
                    <th>Rôle</th>
                    <th>Dossiers actifs</th>
                </tr>
                </thead>
                <tbody>
                {% with can_edit=perms.carrefour.change_contact %}
                {% for contact in object_list %}
                    <tr>
                        {% if perms.carrefour.delete_contact %}
                        <td>
                            <input type="checkbox" class="form-check-input" name="doublons" value="{{ contact.pk }}">
                        </td>
                        {% endif %}
                        <td>{% if can_edit %}<a href="{% url 'contact-edit' contact.pk %}">{% endif %}
                            {{ contact.nom_prenom }}{% if can_edit %}</a>{% endif %}
                        </td>
                        <td>{{ contact.telephone }}</td>
                        <td>{{ contact.email }}</td>
                        <td>{{ contact.service.sigle }}</td>
                        <td>{{ contact.role.nom }}</td>
                        <td align="center">
                            <button type="button" class="btn btn-xs btn-outline-primary js-dossier-contact"
                                    data-bs-toggle="modal"
                                    data-bs-target="#dossierContactModal"
                                    data-url="{% url 'contact-dossier' contact.pk %}" >
                                {{ contact.dossiers|length }}
                            </button>
                        </td>
                    </tr>
                {% endfor %}
                {% endwith %}
                </tbody>
            </table>
            {% if perms.carrefour.delete_contact %}
            <button type="submit" class="btn btn-warning">Fusionner…</button>
            {% endif %}
        </div>
    </div>
    </form>

<!-- Modal -->
<div class="modal" id="dossierContactModal" tabindex="-1" role="dialog" aria-labelledby="dossierContactModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="dossierContactModalLabel"></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Fermer"></button>
      </div>
      <div class="modal-body"></div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fermer</button>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/carrefour/contact_merge.html
{% extends "base.html" %}

{% block extra_javascript %}
<script>
$(document).ready(function() {
    $("#mergeTable").on('click', '.js-copy', function() {
        var currentRow=$(this).closest("tr");
        var value = $.trim($(this).parent().text());
        currentRow.find("td:eq(0)").find("input[type='text']").val(value);
    });
});
</script>
{% endblock %}
{% block content %}
    <div class="row border-bottom mb-5">
        <div class="col-12 lead">Fusionner les contacts sélectionnés</div>
        <div class="col-12 mt-3 fst-6 fst-italic">
            Compléter les champs du "Contact à conserver" et/ou recopier les champs en cliquant sur
            <img src="{% static 'img/arrow-left-square.svg' %}" class="icon"
                style="background-color:#d1e7dd;">.&nbsp;
            Les "contacts à fusionner" seront supprimés!
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col">
            <form action="." method="post">{% csrf_token %}
                {{ form.doublons }}
                <table id="mergeTable" class="table table-sm">
                    <tr>
                        <th width="15%" class="table-success">Contact à conserver</th>
                        {% for contact in contacts %}
                        <th width="15%" class="table-warning" style="padding-left:15px;">
                            Contact {{ forloop.counter }} à fusionner
                        </th>
                        {% endfor %}
                    </tr>
                    {% for field in form %}
                    {% if field.name != "doublons" %}
                    <tr>
                        <td>
                            <div class="row mb-1">
                                <label for="{{ field.id_for_label }}" class="col-sm-3 col-form-label">
                                    {{ field.label }}
                                </label>
                                <div class="col-sm-9">{{ field }}</div>
                              </div>
                        </td>
                        {% for contact in contacts %}
                        <td style="padding-left:15px; padding-top:10px;">
                            {{ contact|get_field_for_merge:field.name|default:'' }}
                            {% if field.name not in "role,service" and contact|get_field_for_merge:field.name %}
                            <img src="{% static 'img/arrow-left-square.svg' %}"
                                 style="background-color:#d1e7dd;"
                                 class="icon js-copy"
                                 title="Recopier l'information">
                            {% endif %}
                        </td>
                        {% endfor %}
                    </tr>
                    {% endif %}
                    {% endfor %}
                </table>
                {% include "actions.html" %}
            </form>
        </div>
    </div>
{% endblock %}

templates/carrefour/derogation_change.html
{% extends "base.html" %}

{% block content %}
    <div class="row justify-content-center mt-3 mb-3">
        <div class="col-md-4 border-bottom ">
            <p class="lead">Nouvelle dérogation pour saisie tardive pour</p>
            <p class="lead">{{ form.educ.nom_prenom }}</p>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-md-4">
            <form action="." method="post">{% csrf_token %}
                <table class="table">
                {{ form.as_table }}
                    <tr>
                        <td colspan="2">Pendant les jours mentionnés, le contrôle pour la saisie tardive des prestations est supprimée.</td>
                    </tr>
                </table>
                {% include 'actions.html' %}

            </form>
        </div>
    </div>
{% endblock %}

templates/carrefour/export.html
{% extends "base.html" %}

{% block content %}
    <div class="row border-bottom mb-3">
        <div class="col"><p class="lead">Exportation mensuelle</p></div>
    </div>
    <div class="row justify-content-center">
        <div class="col-4">
            <p class="lead">Exportation des données personnelles vers Excel </p>
            <form class="selection_form" action="#" method="post">{% csrf_token %}
                <table class="table table-sm table-borderless">
                    {{ form.as_table }}
                </table>
                <div class="pt-3 border-top text-end">
                    <input type="submit" value="Exporter">
                </div>
            </form>
        </div>
    </div>
{% endblock %}

templates/carrefour/role_list.html
{% extends "base.html" %}

{% block content %}
    <div class="row border-bottom mb-3">
        <div class="col"><p class="lead">Rôles</p></div>
        {% if perms.carrefour.add_role %}
        <div class="col text-end">
            <a class="btn btn-sm btn-outline-primary" href="{% url 'role-add' %}">Nouveau</a>
        </div>
        {% endif %}
    </div>
    <div class="row">
        <div class="col">
            <table id="list_role" class="table table-sm table-hover">
                <thead class="table-light">
                    <tr>
                        <th>Nom</th>
                        <th>Rôle familial</th>
                    </tr>
                </thead>
                <tbody>
                    {% with can_edit=perms.carrefour.change_role %}
                    {% for role in object_list %}
                    <tr>
                        <td>{% if can_edit and role.editable %}<a href="{% url 'role-edit' role.pk %}">{% endif %}{{ role.nom }}{% if can_edit and role.editable %}</a>{% endif %}</td>
                        <td>{{ role.famille|yesno:"oui,non" }}</td>
                    </tr>
                    {% endfor %}
                    {% endwith %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}