batoude/urls.py
from django.urls import path

from batoude import views

urlpatterns = [
    path('person/list/', views.BeneficiaireListView.as_view(), name='batoude-person-list'),
    path('person/add/', views.BeneficiaireCreateView.as_view(), name='batoude-person-add'),
    path('person/<int:pk>/edit/', views.BeneficiaireEditView.as_view(), name='batoude-person-edit'),
    path('person/<int:pk>/journal/', views.JournalListView.as_view(), name='batoude-journal-list'),
    path('person/<int:pk>/famille/list/', views.MembreFamilleListView.as_view(), name='batoude-famille-list'),
    path('person/<int:pk>/famille/add/', views.MembreFamilleCreateView.as_view(), name='batoude-famille-add'),
    path('person/<int:pk>/famille/<int:obj_pk>/edit/', views.MembreFamilleUpdateView.as_view(),
         name='batoude-famille-edit'),
    path('person/<int:pk>/assurance/edit/', views.AssuranceUpdateView.as_view(),
         name='batoude-assurance-edit'),
    path('person/<int:pk>/medic/edit/', views.MedicationUpdateView.as_view(),name='batoude-medication-edit'),
    path('suivis_termines/', views.SuivisTerminesListView.as_view(), name='batoude-suivis-termines'),
    # Prestations
    path('prestation/menu/', views.PrestationMenuView.as_view(), name='batoude-prestation-menu'),
    path('person/<int:pk>/prestation/list/', views.PrestationListView.as_view(), name='batoude-prestation-list'),
    path('person/<int:pk>/prestation/add/', views.PrestationCreateView.as_view(), name='batoude-prestation-add'),
    path('person/<int:pk>/prestation/<int:obj_pk>/edit/', views.PrestationUpdateView.as_view(),
         name='batoude-prestation-edit'),
    path('person/<int:pk>/prestation/<int:obj_pk>/delete/', views.PrestationDeleteView.as_view(),
         name='batoude-prestation-delete'),
    path('prestation_gen/list/', views.PrestationListView.as_view(), name='batoude-prestation-gen-list'),
    path('prestation_gen/add/', views.PrestationCreateView.as_view(), name='batoude-prestation-gen-add'),
    path('prestation/recap-perso/', views.PrestationRecapPersoListView.as_view(),
         name='batoude-prestation-recap-perso'),

    path('prestations/list/', views.AdminPrestationListView.as_view(),
         name='batoude-prestation-adminlist'),
    path('person/<int:pk>/contact/', views.ContactListView.as_view(), name='batoude-contact-list'),
    path('person/<int:pk>/contact/<int:obj_pk>/remove/', views.ContactRemoveView.as_view(),
         name='batoude-contact-remove'),
    path('person/<int:pk>/contact/add/', views.ContactAddView.as_view(), name='batoude-contact-add'),
    path('person/<int:pk>/contact/<int:obj_pk>/edit/', views.ContactUpdateView.as_view(), name='batoude-contact-edit'),

    path('person/<int:pk>/print-coord/', views.CoordPDFView.as_view(), name='batoude-print-coordinates'),
    path('person/<int:pk>/print-journal/', views.JournalPDFView.as_view(), name='batoude-print-journal'),

    path('person/<int:pk>/agenda/', views.AgendaUpdateView.as_view(), name='batoude-person-agenda'),

    path('person/<int:pk>/doc/list/', views.DocumentListView.as_view(), name='batoude-doc-list'),
    path('person/<int:pk>/doc/upload/', views.DocumentUploadView.as_view(), name='batoude-doc-upload'),
    path('person/<int:pk>/doc/<int:doc_pk>/delete/', views.DocumentDeleteView.as_view(), name='batoude-doc-delete'),

    path('person/<int:pk>/bilan/<str:typ>/add/', views.BilanCreateView.as_view(), name='batoude-bilan-create'),
    path('person/<int:pk>/bilan/<int:obj_pk>/edit/', views.BilanEditView.as_view(), name='batoude-bilan-edit'),
    path('person/<int:pk>/bilan/<int:obj_pk>/print/', views.BilanPrintView.as_view(), name='batoude-bilan-print'),
]

ser/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('person/list/', views.PersonListView.as_view(), name='asap-person-list'),
    path('person/enveille/list/', views.PersonEnVeilleListView.as_view(), name='asap-person-veille'),
    path('person/add/', views.PersonCreateView.as_view(), name='asap-person-add'),
    path('person/<int:pk>/change/', views.PersonUpdateView.as_view(), name='asap-person-change'),
    path('person/<int:pk>/delete/', views.PersonDeleteView.as_view(), name='asap-person-delete'),

    path('person/<int:pk>/journal/', views.JournalListView.as_view(), name='asap-journal-list'),
    path('person/<int:pk>/journal/add/', views.JournalCreateView.as_view(), name='asap-journal-add'),
    path('person/<int:pk>/journal/<int:obj_pk>/edit/', views.JournalUpdateView.as_view(), name='asap-journal-change'),

    path('person/<int:pk>/upload/', views.DocumentUploadView.as_view(), name='person-doc-upload'),
    path('person/<int:pk>/doc/<int:doc_pk>/delete/', views.DocumentDeleteView.as_view(), name='person-doc-delete'),

    path('place/list/', views.PlaceListView.as_view(), name='asap-place-list'),
    path('place/add/', views.PlaceCreateView.as_view(), name='asap-place-add'),
    path('place/<int:pk>/change/', views.PlaceUpdateView.as_view(), name='asap-place-change'),
    path('place/<int:pk>/delete/', views.PlaceDeleteView.as_view(), name='asap-place-delete'),

    path('utilisateur/dal/', views.UtilisateurAsapAutocompleteView.as_view(), name='asap-utilisateur-autocomplete'),


    path('prestation/list/', views.PrestationListView.as_view(), name='asap-prestation-list'),
    path('prestation/add/', views.PrestationCreateView.as_view(), name='asap-prestation-add'),
    path('prestation/<int:pk>/change/', views.PrestationUpdateView.as_view(), name='asap-prestation-change'),
    path('prestation/extra/<str:action>/add/', views.PrestationExtraAddView.as_view(),
         name='asap-prestation-extra-add'),
    path('prestation/<int:pk>/delete/', views.PrestationDeleteView.as_view(), name='asap-prestation-delete'),
    path('tshm/create/', views.TshmCreateView.as_view(), name="asap-tshm-add"),
    path('tshm/<int:pk>/change/', views.TshmUpdateView.as_view(), name="asap-tshm-change"),
    path('tshm/list/', views.TshmListView.as_view(), name='asap-tshm-list'),

]

batoude/models.py
import calendar
import os
from datetime import date, timedelta
from django.db import models
from django.db.models import Q, Sum, F, Count
from django.db.models.functions import Coalesce
from django.utils import timezone

from aemo.models import Etape as AemoEtape
from carrefour.models import Contact, PrestationBase, Utilisateur
from carrefour.utils import delay_for_destruction, format_duree, format_d_m_Y, random_string_generator
from common import choices
from common.fields import ChoiceArrayField


class Etape(AemoEtape):
    """
        1. Numéro d'ordre pour tri dans la vue
        2. Code
        3. Affichage dans tableau
        4. Nom visible de l'étape
        5. Code de l'étape suivante
        6. Délai jusqu'à l'échéance (en jours)
        7. Code de l'étape précédente
        8. Date obligatoire précédente (code ou '')
        9. Bool.
    """
    def __init__(self, num, code, abrev, nom, suivante, delai, precedente, preced_oblig, oblig, actif=True):
        super().__init__(num, code, abrev, nom, suivante, delai, precedente, preced_oblig, oblig)
        self.actif = actif


class PersonneBase(models.Model):
    nom = models.CharField('Nom', max_length=40)
    prenom = models.CharField('Prénom', max_length=40)
    naissance = models.DateField('Date de naissance', null=True, blank=True, default=None)
    telephone = models.CharField('Téléphone', max_length=40, blank=True)
    email = models.EmailField('Courriel', blank=True)
    genre = models.CharField(
        'Genre', max_length=1, choices=(('M', 'M'), ('F', 'F'), ('X', 'Non binaire')), blank=True
    )
    rue = models.CharField('Rue', max_length=30, blank=True)
    npa = models.CharField('NPA', max_length=4, blank=True)
    localite = models.CharField('Localité', max_length=30, blank=True)
    permis = models.CharField('Nationalité, Permis/séjour', max_length=30, blank=True)
    validite = models.DateField('Date validité', blank=True, null=True)
    emploi = models.CharField('Emploi actuel', max_length=40, blank=True)
    remarque = models.CharField('Remarque', max_length=200, blank=True)

    class Meta:
        abstract = True

    def nom_prenom(self):
        return f'{self.nom} {self.prenom}'

    def adresse_officielle(self):
        sep = ', ' if self.rue else ''
        return f'{self.rue}{sep}{self.npa} {self.localite}'.strip()

    def __str__(self):
        return self.nom_prenom()


class Beneficiaire(PersonneBase):
    WORKFLOW = {
        'demande': Etape(
            1, 'demande', 'dem', 'Demande', 'entretien', 30, 'demande', 'demande', True
        ),
        'entretien': Etape(
            2, 'entretien', 'ent', 'Entretien', 'admission', 30, 'demande', 'demande', True
        ),
        'admission': Etape(
            3, 'admission', 'adm', 'Admission', 'appartement', 90, 'entretien', 'entretien', True
        ),
        'appartement': Etape(
            4, 'appartement', 'app', 'Appartement', '6mois', 00, 'admission', 'admission', True
        ),
        '6mois': Etape(
            5, '6mois', '6m', '6 mois', '12mois', 180, 'appartement', 'appartement', True, False
        ),
        '12mois': Etape(
            6, '12mois', '12m', '12 mois', '18mois', 180, '6mois', '6mois', True, False
        ),
        '18mois': Etape(
            7, '18mois', '18m', '18 mois', '24mois', 180, '12mois', '12mois', True, False
        ),
        '24mois': Etape(
            8, '24mois', '24m', '24 mois', '30mois', 180, '12mois', '12mois', True, False
        ),
        '30mois': Etape(
            9, '30mois', '30m', '30 mois', 'prolongation', 180, '24mois', '24mois', True, False
        ),
        '36mois': Etape(
            10, '36mois', 'pro', 'Prolongation', 'sortie', 180,  '30mois', '30mois', True, False
        ),
        'sortie': Etape(
            11, 'sortie', 'sor', 'Sortie', 'archivage', 30, 'prolongation', 'admission', True
        ),
        'archivage': Etape(
            12, 'archivage', 'arc', 'Archivage', None, 300, 'sortie', 'sortie', True, False
        ),
    }

    rue_actuelle = models.CharField('Rue act.', max_length=30, blank=True)
    npa_actuelle = models.CharField('NPA act.', max_length=4, blank=True)
    localite_actuelle = models.CharField('Localité act.', max_length=30, blank=True)
    region = models.CharField('Région', max_length=12, choices=choices.REGIONS_CHOICES, blank=True)

    caisse_mal_acc = models.CharField('Caisse maladie-acc.', max_length=50, blank=True)
    no_assure_lamal = models.CharField("No d'assuré", max_length=30, blank=True)
    assurance_rc = models.CharField('Assurance RC', max_length=50, blank=True)
    no_avs = models.CharField("N° AVS", max_length=16, blank=True)
    assurance_accident = models.BooleanField('Assurance avec accident', blank=True, null=True, default=None)
    no_assure_compl = models.CharField("No d'assuré compl.", max_length=30, blank=True)
    ass_maladie_compl = models.CharField('Ass.-maladie compl.', max_length=50, blank=True)
    loisirs = models.TextField('Loisirs/passions', blank=True)
    scolarite = models.TextField('Situation scolaire', blank=True)
    autorite_parentale = models.CharField(
        "Autorité parentale", max_length=20, choices=choices.AUTORITE_PARENTALE_CHOICES, blank=True
    )
    statut_marital = models.CharField("Statut marital", max_length=20, choices=choices.STATUT_MARITAL_CHOICES,
                                      blank=True)
    statut_financier = models.CharField(
        'Statut financier', max_length=20, choices=choices.STATUT_FINANCIER_CHOICES, blank=True
    )
    monoparentale = models.BooleanField('Famille monoparent.', null=True, blank=True)
    reseau = models.ManyToManyField(Contact, blank=True)
    referent_ope = models.ForeignKey(
        Contact, blank=True, null=True, on_delete=models.PROTECT, related_name="suivisbatoude",
    )
    referent_ope2 = models.ForeignKey(
        Contact, blank=True, null=True, on_delete=models.PROTECT, related_name="suivisbatoude2",
    )
    mandat_ope = ChoiceArrayField(
        models.CharField(max_length=65, choices=choices.MANDATS_OPE_CHOICES, blank=True),
        verbose_name="Mandat OPE", blank=True, null=True,
    )

    provenance = models.CharField(
        'Provenance av. admission', max_length=30, choices=choices.PROVENANCE_DESTINATION_CHOICES, blank=True
    )
    destination = models.CharField(
        'Destination après suivi', max_length=30, choices=choices.DESTINATION_BATOUDE_CHOICES, blank=True
    )
    service_orienteur = models.CharField(
        "Orienté vers la Batoude par", max_length=15, choices=choices.SERVICE_ORIENTEUR_ASAEF_CHOICES, blank=True
    )
    autoevaluation = models.SmallIntegerField("Auto-évaluation", blank=True, null=True, choices=choices.SCORE_CHOICES)
    motif_fin_suivi = models.CharField(
        'Motif de fin de suivi', max_length=20, choices=choices.MotifsFinSuivi.choices, blank=True
    )
    date_demande = models.DateField("Date de la demande", null=True)
    date_entretien = models.DateField("Date entretien d'info.", null=True, blank=True, default=None)
    date_validation = models.DateField("Date demande validée", null=True, blank=True, default=None)
    date_admission = models.DateField("Date d'admission", null=True, blank=True, default=None)
    date_appartement = models.DateField("Date entrée appartement", null=True, blank=True, default=None)
    date_prolongation = models.DateField("Date prolongation", null=True, blank=True, default=None)
    date_sortie = models.DateField("Date de sortie", null=True, blank=True, default=None)
    date_facturation = models.DateField('Début de la facturation', null=True, blank=True)
    archived_at = models.DateTimeField('Archivée le', blank=True, null=True)

    class Meta:
        verbose_name = 'Bénéficiaire BATOUDE'
        verbose_name_plural = 'Bénéficiaires BATOUDE'
        ordering = ('nom', 'prenom')
        permissions = (
            ('view_batoude', 'Consulter les dossiers BATOUDE'),
            ('manage_batoude', 'RE BATOUDE'),
            ('change_batoude', 'Gérer les dossiers Batoude'),
        )

    def get_mandat_ope_display(self):
        return ", ".join(
            [dict(choices.MANDATS_OPE_CHOICES)[v] for v in self.mandat_ope]
        ) if self.mandat_ope else ''

    def mere(self):
        return self.membres_famille.filter(role='mere').first()

    def pere(self):
        return self.membres_famille.filter(role='pere').first()

    def can_edit(self, user):
        return user.has_perm('batoude.change_batoude') and self.date_sortie is None

    def prestations_historiques(self):
        return PrestationBase.prestations_historiques(self.prestations_batoude.all())

    def jours_factures_par_mois(self, mydate):
        nbre_jours_absence = self.absences.filter(
            date_debut__year=mydate.year, date_debut__month=mydate.month
        ).aggregate(total=Sum('nbre_jour'))['total'] or 0
        return calendar.monthrange(mydate.year, mydate.month)[1] - nbre_jours_absence

    def prestations_du_mois(self):
        """
        Retourne le détail des prestations pour ce bénéficiaire pour le mois courant
        """
        date_ref = date(date.today().year, date.today().month, 1)
        return self.prestations_batoude.filter(date_prestation__gte=date_ref)

    def temps_total_prestations(self, interv=None):
        """
        Temps total des prestations liées à ce bénéficiare, quel que soit le nombre
        de membres suivis.
        Filtré facultativement par intervenant.
        """
        prest = self.prestations_batoude if interv is None else self.prestations_batoude.filter(intervenant=interv)
        return prest.annotate(
            nbre_inter=Count('intervenants')
        ).aggregate(
            total=Sum(F('duree') * F('nbre_inter'), output_field=models.DurationField())
        )['total'] or timedelta()

    @classmethod
    def benef_actifs(cls, mydate):
        annee = mydate.year
        mois = mydate.month
        debut_mois = date(annee, mois, 1)

templates/batoude/agenda_edit.html
{% extends "base.html" %}

{% block boutons_droite %}
    {% include 'batoude_boutons.html' with active='agenda' %}
{% endblock %}

{% block content %}
    <div class="row border-bottom mb-5">
        <div class="col lead">Bénéficiaire: {{ person.nom_prenom }} - {{ person.adresse_officielle }}</div>
        <div class="col text-end lead">Calendrier de suivi</div>
    </div>

    <form action= "." method="post">{% csrf_token %}
        <input type="hidden" name="beneficiaire" value="{{ object.pk }}">
        {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                <strong>{{ error }}</strong>
            </div>
        {% endfor %}
        <div class="row mt-2">
            <div class="col-md-2 offset-1">{% duree_suivi person %}</div>
            <div class="col-md-2 offset-6 text-end">{% check_majorite person %}</div>
        </div>
        <div class="row justify-content-center mt-2">
            <div class="col-md-2 text-center p-3" style="background-color:#FEF9C1">
                <div class="h5 mb-3">DEMANDE</div>
                <div>Demande déposée le</div>
                <div class="d-flex justify-content-center mb-3">{{ form.date_demande.errors }}{{ form.date_demande }}</div>
                <div>Entretien d'information le</div>
                <div class="d-flex justify-content-center mb-3">{{ form.date_entretien.errors }}{{ form.date_entretien }}</div>
                <div>Demande validée le</div>
                <div class="d-flex justify-content-center mb-3">{{ form.date_validation.errors }}{{ form.date_validation }}</div>
                {% if form.instance.date_demande %}
                    {% bouton_bilan person 'demande' %}
                {% endif %}

                {% if mode == 'preparation' %}
                <div id="abandon" class="border p-3" style="width:20%;background-color:#FFDDAA;">
                    <div><em>Si abandon du dossier:</em></div>
                    <div>Motif de fin</div>
                    <div>{{ form.motif_fin_suivi.errors }}{{ form.motif_fin_suivi }}</div>
                </div>
                {% endif %}
            </div>
            <div class="col-md-2 text-center p-3" style="background-color:#D0F2D1">
                <div class="h5 mb-3">ADMISSION</div>
                <div>Entretien d'admission le</div>
                <div class="d-flex justify-content-center mb-3">{{ form.date_admission.errors }}{{ form.date_admission }}</div>
                {% if form.instance.date_admission %}
                    {% bouton_bilan person 'admission' %}
                {% endif %}
            </div>
            <div class="col-md-2 text-center p-3" style="background-color:#B38341">
                <div class="h5 mb-3">AUTONOMISATION</div>
                <div>Entrée en appart. le</div>
                <div class="d-flex justify-content-center mb-3">{{ form.date_appartement.errors }}{{ form.date_appartement }}</div>
                {% if form.instance.date_appartement %}
                    {% bouton_bilan person 'autonomisation' %}
                {% endif %}
            </div>
            <div class="col-md-2 text-center p-3" style="background-color:#F6D1BD">
                <div class="h5 mb-3">PROLONGATION</div>
                {% if form.instance.date_appartement %}
                    <div>Début de la prolongation le</div>
                    <div class="d-flex justify-content-center mb-3">{{ form.date_prolongation.errors }}{{ form.date_prolongation }}</div>
                    {% bouton_bilan person 'prolongation' %}
                {% endif %}
            </div>
            <div class="col-md-2 text-center p-3" style="background-color:#dccac8">
                <div class="h5 mb-3">FIN</div>
                {% if mode == 'suivi' %}
                <div class="fin p-3 border" style="background-color:#F8F8F8;">
                    <div>Date de fin du suivi</div>
                    <div class="mb-3">{{ form.date_sortie.errors }}{{ form.date_sortie }}</div>
                    <div>Motif de fin du suivi</div>
                    <div class="mb-3">{{ form.motif_fin_suivi.errors }}{{ form.motif_fin_suivi }}</div>
                    <div>Destination</div>
                    <div class="mb-3">{{ form.destination.errors }}{{ form.destination }}</div>
                    <div>Auto-évaluation</div>
                    <div>{{ form.autoevaluation.errors }}{{ form.autoevaluation }}</div>
                </div>
                {% endif %}
            </div>
        </div>
        <div class="row">
            <div class="col">
                {% if not closed and person|can_edit:user %}
                {% include "actions.html" %}
                {% endif %}
            </div>
        </div>
    </form>
{% endblock %}

templates/batoude/assurance_edit.html
{% extends "base.html" %}

{% block extra_javascript %}
<script type="text/javascript">

    $(document).ready(function() {
        $("#id_btn_copy").click(function(){
            $("#id_rue_actuelle").val($("#id_rue").val());
            $("#id_npa_actuelle").val($("#id_npa").val());
            $("#id_localite_actuelle").val($("#id_localite").val());
        });

    });
</script>
{% endblock %}

{% block boutons_droite %}
        {% include 'batoude_boutons.html' with active='admin' %}
{% endblock %}

{% block content %}
    <div class="row border-bottom mb-5">
        <div class="col lead">{{ person|benef_nom_adresse }}</div>
        <div class="col text-end lead">Assurances</div>
    </div>
    <div class="row justify-content-center">
        <div class="col-5">
            <form name="person_batoude" action="#" method="post">{% csrf_token %}
                <table class="table table-sm table-borderless">
                    {{ form.as_table }}
                </table>
                {% if person|can_edit:user %}
                {% include 'actions.html' %}
                {% endif %}
            </form>
        </div>
    </div>
{% endblock %}

templates/batoude/beneficiaire_edit.html
{% extends "base.html" %}

{% block extra_javascript %}
<script type="text/javascript">

    $(document).ready(function() {
        $("#id_btn_copy").click(function(){
            $("#id_rue_actuelle").val($("#id_rue").val());
            $("#id_npa_actuelle").val($("#id_npa").val());
            $("#id_localite_actuelle").val($("#id_localite").val());
        });

    });
</script>
{% endblock %}

{% block boutons_droite %}
    {% if form.instance.pk %}
        {% include 'batoude_boutons.html' with active='coordonnees' %}
    {% endif %}
{% endblock %}

{% block content %}
    <div class="row border-bottom mb-5">
        <div class="col lead">{{ person|benef_nom_adresse }}</div>
        <div class="col text-end lead">Coordonnées
            {% if form.instance.pk %}
                <a href="{% url 'batoude-print-coordinates' person.pk  %}"><img class="icon" src="{% static 'img/printer.png' %}"></a>
            {% endif %}
        </div>
    </div>
    <form name="person_batoude" action="#" method="post">{% csrf_token %}
        <div class="row justify-content-center">
            <div class="col-10">
                <div class="row mb-3">
                    {% form_item form.nom 6 %}
                    {% form_item form.prenom 6 %}
                </div>
                <div class="row mb-3">
                    {% form_item form.naissance 2 %}
                    {% form_item form.genre 2 %}
                    {% form_item form.telephone 3 %}
                    {% form_item form.email 5 %}
                </div>
                <div class="row mb-3">
                    <div class="col-2 fw-bold">Adresse officielle :</div>
                    {% form_item form.rue 4 %}
                    {% form_item form.npa 1 %}
                    {% form_item form.localite 5 %}
                </div>
                <div class="row mb-3">
                    <div class="col-2 fw-bold">Adresse actuelle :<br/>
                    <a href="#" id="id_btn_copy" class="btn btn-sm btn-outline-primary" style="font-size:80%">copier
                        adresse</a></div>
                    {% form_item form.rue_actuelle 4 %}
                    {% form_item form.npa_actuelle 1 %}
                    {% form_item form.localite_actuelle 5 %}
                </div>
                <div class="row mb-3">
                    <div class="col-2 fw-bold">Région</div>
                    <div class="col-4">{{ form.region }}</div>
                </div>
                <div class="row mb-3">
                    <div class="col-6 fw-bold">Référent-e OPE:
                        <div class="input-group mt-2">
                            <span class="input-group-text"
                                title="{{ person.referent_ope.email }}/{{ person.referent_ope.telephone }}">No 1
                            </span>{{ form.referent_ope }}
                        </div>
                        <div class="input-group mt-3">
                            <span class="input-group-text"
                                title="{{ person.referent_ope2.email }}/{{ person.referent_ope2.telephone }}">No 2
                            </span>{{ form.referent_ope2 }}
                        </div>
                        <div class="mt-3">{{ form.mandat_ope }}</div>
                    </div>
                    <div class="col-6">
                        {% form_item form.autorite_parentale 12 %}
                        <p class="mt-3">{{ form.date_demande.label_tag }}{{ form.date_demande.errors }}{{ form.date_demande }}</p>
                    </div>

                </div>
                {% if not form.instance.pk or form.instance|can_edit:user %}
                    {% include "actions.html" %}
                {% endif %}

            </div>
        </div>
    </form>
{% endblock %}

templates/batoude/bilan_change.html
{% extends "base.html" %}

{% block content %}
    <div class="row border-bottom mt-3 mb-3 justify-content-between">
        <div class="col">
            <p class="lead">Bénéficiaire: {{ person.nom_prenom }} - {{ person.adresse_officielle }}</p>
        </div>
        <div class="col-md-3">{{ form.typ }}</div>
    </div>
    <div class="row mb-5 justify-content-center">
        <div class="col-10">
            <form name="BilanBatoudeForm" action="." method="post">{% csrf_token %}
                {% for hidden in form.hidden_fields %}{{ hidden }}{% endfor %}
                {% for field in form.visible_fields %}
                <div class="row mb-3">
                    <div class="col-md-3">{{ field.label_tag }}</div>
                    <div class="col-md-9">{{ field }}{{ field.errors }}</div>
                </div>
                {% endfor %}
                {% if person|can_edit:user %}
                {% include "actions.html" %}
                {% endif %}
            </form>
        </div>
    </div>
{% endblock %}

templates/batoude/contact_add_form.html
{% extends "carrefour/form_in_popup.html" %}

{% block after_table %}
<div>
    <a class="btn btn-sm btn-outline-primary mt-3" role="button"
       href="{% url 'contact-add' %}?forpers=benef-{{ benef.pk }}">Créer un nouveau contact
    </a>
</div>
{% endblock %}

templates/batoude/contact_list.html
{% extends "base.html" %}

{% block boutons_droite %}
    {% include 'batoude_boutons.html' with active='contact' %}
{% endblock %}

{% block content %}
    <div class="row mb-5 mt-3 py-3 border-bottom">
        <div class="col lead">Contacts de {{ person|benef_nom_adresse }}</div>
        <div class="col text-end">
              {% if not archived and person|can_edit:user %}
               <a href="{% url 'batoude-contact-add' person.pk %}"
                  class="btn btn-sm btn-outline-primary ms-5 js-edit">Ajouter un contact
               </a>
              {% endif %}
        </div>
    </div>
    <div class="row mb-3 justify-content-center">
        <div class="col-12">
           <form action="#" method="post">{% csrf_token %}
              <input type="hidden" name="famille" value="{{ famille.pk }}">
              <table id="t_contacts" class="table table-sm table-borderless table-hover">
                 <thead class="table-light">
                    <tr>
                        <th>Nom, prénom</th><th>Rôle/Act./prof.</th><th>Téléphone</th>
                        <th>Courriel</th><th width="60px">Action</th>
                    </tr>
                 </thead>
                 <tbody>
                    <tr>
                       <td>{{ person.referent_ope.nom_prenom }}</td>
                       <td>{{ person.referent_ope }}</td>
                       <td>{{ person.referent_ope.telephone }}</td>
                       <td>{{ person.referent_ope.email }}</td>
                       <td></td>
                    </tr>
                    {% for obj in person.reseau.all %}
                       <tr>
                           <td>{{ obj.nom_prenom }}</td>
                           <td>{{ obj|role_profession }}</td>
                           <td>{{ obj.telephone }}</td>
                           <td>{{ obj.email }} </td>
                           <td align="center">
                              {% if person|can_edit:user %}
                              <button class="btn btn-xs btn-danger mr-2 confirm" title="Retirer ce contact"
                                 data-confirm="Voulez-vous vraiment retirer ce contact ?"
                                 formaction="{% url 'batoude-contact-remove' person.pk obj.pk %}">X
                              </button>
                              {% if perms.carrefour.change_contact %}
                                 <a title="Modifier ce contact"
                                    href="{% url 'batoude-contact-edit' person.pk obj.pk %}">
                                    <img src="{% static 'admin/img/icon-changelink.svg' %}">
                                 </a>
                              {% endif %}
                              {% endif %}
                           </td>
                       </tr>
                    {% endfor %}
                 </tbody>
             </table>
           </form>
        </div>
    </div>
{% endblock %}