ser/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('person/list/', views.PersonListView.as_view(), name='asap-person-list'),
    path('person/enveille/list/', views.PersonEnVeilleListView.as_view(), name='asap-person-veille'),
    path('person/add/', views.PersonCreateView.as_view(), name='asap-person-add'),
    path('person/<int:pk>/change/', views.PersonUpdateView.as_view(), name='asap-person-change'),
    path('person/<int:pk>/delete/', views.PersonDeleteView.as_view(), name='asap-person-delete'),

    path('person/<int:pk>/journal/', views.JournalListView.as_view(), name='asap-journal-list'),
    path('person/<int:pk>/journal/add/', views.JournalCreateView.as_view(), name='asap-journal-add'),
    path('person/<int:pk>/journal/<int:obj_pk>/edit/', views.JournalUpdateView.as_view(), name='asap-journal-change'),

    path('person/<int:pk>/upload/', views.DocumentUploadView.as_view(), name='person-doc-upload'),
    path('person/<int:pk>/doc/<int:doc_pk>/delete/', views.DocumentDeleteView.as_view(), name='person-doc-delete'),

    path('place/list/', views.PlaceListView.as_view(), name='asap-place-list'),
    path('place/add/', views.PlaceCreateView.as_view(), name='asap-place-add'),
    path('place/<int:pk>/change/', views.PlaceUpdateView.as_view(), name='asap-place-change'),
    path('place/<int:pk>/delete/', views.PlaceDeleteView.as_view(), name='asap-place-delete'),

    path('utilisateur/dal/', views.UtilisateurAsapAutocompleteView.as_view(), name='asap-utilisateur-autocomplete'),


    path('prestation/list/', views.PrestationListView.as_view(), name='asap-prestation-list'),
    path('prestation/add/', views.PrestationCreateView.as_view(), name='asap-prestation-add'),
    path('prestation/<int:pk>/change/', views.PrestationUpdateView.as_view(), name='asap-prestation-change'),
    path('prestation/extra/<str:action>/add/', views.PrestationExtraAddView.as_view(),
         name='asap-prestation-extra-add'),
    path('prestation/<int:pk>/delete/', views.PrestationDeleteView.as_view(), name='asap-prestation-delete'),
    path('tshm/create/', views.TshmCreateView.as_view(), name="asap-tshm-add"),
    path('tshm/<int:pk>/change/', views.TshmUpdateView.as_view(), name="asap-tshm-change"),
    path('tshm/list/', views.TshmListView.as_view(), name='asap-tshm-list'),

]

ser/models.py
import os
from datetime import date, datetime, timedelta

from django.db import models
from django.db.models import F, Sum
from django.db.models.functions import TruncMonth

from carrefour.models import Contact, Utilisateur, JournalBase
from carrefour.utils import format_d_m_Y, format_duree
from common import choices
from common.fields import ChoiceArrayField


class Person(models.Model):
    STATUS_CHOICES = (
        ('actif', 'Actif'),
        ('veille', 'En veille'),
        ('supprime', 'Supprimé')
    )
    nom = models.CharField('Nom', max_length=40, blank=True)
    prenom = models.CharField('Prénom', max_length=40, unique=True)
    surnom = models.CharField('Surnom', max_length=40, blank=True)
    age_approximatif = models.IntegerField('Âge approximatif', null=True, blank=True)
    date_naissance = models.DateField('Date de naissance', null=True, blank=True)
    telephone = models.CharField('Téléphone', max_length=40, blank=True)
    email = models.EmailField('Courriel', blank=True)
    genre = models.CharField('Genre', max_length=1, choices=(('M', 'M'), ('F', 'F')), default='M')
    rue = models.CharField('Rue', max_length=30, blank=True)
    npa = models.CharField('NPA', max_length=4, blank=True)
    localite = models.CharField('Localité', max_length=30, blank=True)
    remarque = models.TextField('Remarque', blank=True)
    educs = models.ManyToManyField(
        to=Utilisateur, related_name='beneficiaires_suivis', blank=True, verbose_name='Référent ASAP'
    )
    contacts = models.ManyToManyField(
        to=Contact, related_name='beneficiaires', blank=True, verbose_name='Membres du réseau'
    )
    statut = models.CharField("Statut", max_length=20, choices=STATUS_CHOICES, default='actif')
    naissance_jour = models.CharField(
        'Jour', max_length=2, choices=((str(j), str(j)) for j in range(1, 32)), blank=True, default=''
    )
    naissance_mois = models.CharField(
        'Mois', max_length=2, choices=((str(m), str(m)) for m in range(1, 13)), blank=True, default=''
    )
    naissance_annee = models.CharField('Année', max_length=4, blank=True)
    region = models.CharField('Région', max_length=12, choices=choices.REGIONS_CHOICES, blank=True)
    motif_demande = ChoiceArrayField(
        models.CharField(max_length=60, choices=choices.ASAP_MOTIF_DEMANDE),
        verbose_name="Motif de la demande", blank=True, null=True, default=list
    )
    reseau_prof = models.TextField("Réseau professionnel", blank=True)
    reseau_perso = models.TextField("Réseau personnel", blank=True)
    service_orienteur = models.CharField(
        "Orientation par", max_length=20, choices=choices.ASAP_SERVICE_ORIENTEUR, blank=True
    )

    class Meta:
        verbose_name = 'Bénéf. ASAP'
        verbose_name_plural = 'Bénéf. ASAP'
        ordering = ('prenom',)
        permissions = (
            ('view_ser', 'Consulter les dossiers ASAP'),
            ('manage_ser', 'RE ASAP'),
            ('change_ser', 'Gérer les dossiers de l’ASAP')
        )

    def __str__(self):
        return f"{self.prenom} {self.nom}" if self.nom else self.prenom

    @classmethod
    def actives(cls):
        return Person.objects.filter(statut='actif')

    @property
    def nom_prenom(self):
        return f"{self.nom} {self.prenom}"

    def can_edit(self, user):
        return user.has_perm('ser.change_ser')

    @classmethod
    def check_perm_view(cls, user):
        return user.has_perm('ser.view_ser')

    def get_educs(self):
        return ', '.join([educ.nom_prenom for educ in self.educs.all()])


class Place(models.Model):
    LOCALITE_CHOICES = (
        ('', ''),
        ('cdf', 'CDF'),
        ('ll', 'LL')
    )
    nom = models.CharField('Lieu de stationnement', max_length=40)
    localite = models.CharField('Localité', max_length=30, choices=LOCALITE_CHOICES, blank=True)
    version = models.SmallIntegerField('Version')

    class Meta:
        verbose_name = 'Stationnement du BIP'
        verbose_name_plural = 'Stationnements du BIP'
        ordering = ('nom',)
        unique_together = ('localite', 'nom')

    def __str__(self):
        return f"{self.nom}"

    def can_edit(self, user):
        return user.has_perm('ser.change_ser')


class Sortie(models.Model):
    date = models.DateField('Date')
    heure_debut = models.TimeField('Heure de début', null=True, blank=True)
    heure_fin = models.TimeField('Heure de fin', null=True, blank=True)
    lieu = models.ForeignKey(to=Place, on_delete=models.CASCADE, related_name='sorties')
    type_intervention = ChoiceArrayField(
        models.CharField(max_length=65, choices=choices.TYPE_INTERVENTION_CHOICES, blank=True),
        verbose_name="Type d’intervention", blank=True, null=True,
    )
    autre_intervention = models.CharField("Autre interv.", max_length=50, blank=True)

    nbre_garcons = models.IntegerField(verbose_name='jeunes hommes', blank=True, default=0)
    nbre_filles = models.IntegerField(verbose_name='jeunes femmes', blank=True, default=0)
    nbre_non_binaires = models.IntegerField(verbose_name='personnes non binaires', blank=True, default=0)
    suivi_possible = models.IntegerField("Nbre de suivis possibles", blank=True, default=0)
    remarque = models.TextField('Remarque', blank=True)
    educs = models.ManyToManyField(to=Utilisateur, related_name='sorties')

    class Meta:
        verbose_name = "Sortie du BIP"
        verbose_name_plural = "Sorties du BIP"

    def __str__(self):
        return f"{format_d_m_Y(self.date)} - {self.lieu.localite}"

    def can_edit(self, user):
        return user.has_perm('ser.change_ser')

    def get_duree(self):
        if self.heure_debut is None or self.heure_fin is None:
            return timedelta()
        diff = datetime.combine(date.min, self.heure_fin) - datetime.combine(date.min, self.heure_debut)
        return diff if diff >= timedelta() else diff + timedelta(days=1)

    @property
    def get_lieu(self):
        return self.lieu.nom if self.lieu else ''

    @property
    def get_type_intervention(self):
        dct = dict((x, y) for x, y in choices.TYPE_INTERVENTION_CHOICES)
        return ", ".join([dct[item] for item in self.type_intervention]) if self.type_intervention else ''

    @property
    def get_educs(self):
        return ', '.join([educ.sigle for educ in self.educs.all()]) if self.educs else ''


class Journal(JournalBase):
    person = models.ForeignKey(
        Person, related_name='journaux', on_delete=models.CASCADE, verbose_name="Bénéficiaire"
    )
    date = models.DateField('Date')
    duree = models.DurationField('Durée de la prest.', default=timedelta(0))

    class Meta(JournalBase.Meta):
        db_table = 'ser_journalser'
        verbose_name = "Journal ASAP"
        verbose_name_plural = "Journaux ASAP"

    def __str__(self):
        return f"Journal de {self.person} - {self.date}"


class Prestation(models.Model):
    MOTIFS_CHOICES = [('tshm', 'Tshm'), ('bulle', 'Bulle Horaire'), ('pe', 'Point Equipe'), ('autre', 'Autre')]
    auteur = models.ForeignKey(Utilisateur, null=True, on_delete=models.PROTECT, related_name='prestations_asap')
    date = models.DateField('Date')

    nbre_suivi_relationnel = models.IntegerField('Nbre de suivis relationnels', default=0)

    nbre_acc_educatif = models.IntegerField("Nbre d’accompagnements éducatifs", default=0)

    # Anciens champs avant 2022, à supprimer plus tard.
    colloque = models.DurationField('Colloque hebdo.', default=timedelta(0))
    analyse = models.DurationField('Analyse de pratique', default=timedelta(0))
    journee_recul = models.DurationField('Journée Recul', default=timedelta(0))
    bulle = models.DurationField('Bulle horaire hebdomadaire', default=timedelta(0))
    soutien_parental = models.DurationField('Soutien parental', default=timedelta(0))
    accompagnement = models.DurationField('Accompagnement jeunes et familles', default=timedelta(0))
    tshm = models.DurationField('TSHM', default=timedelta(0))
    permanence = models.DurationField('Permanence', default=timedelta(0))
    intervention = models.DurationField('Intervention externe', default=timedelta(0))
    manifestation = models.DurationField('Manifestation', default=timedelta(0))
    reseau = models.DurationField('Rencontre réseau', default=timedelta(0))
    administratif = models.DurationField('Trav. admin.', default=timedelta(0))

    duree_admin = models.DurationField('Travaux. admin.', default=timedelta(0))
    duree_projet = models.DurationField('Projet et intervention', default=timedelta(0))
    duree_reseau = models.DurationField('Rencontre réseau', default=timedelta(0))
    duree_suivi = models.DurationField('Suivi et jeunes', default=timedelta(0))

    motif = models.CharField('Motif', choices=MOTIFS_CHOICES)
    duree_prestation = models.DurationField('Durée', blank=True, default=timedelta(0))
    homme = models.SmallIntegerField('Jeunes hommes', default=0)
    femme = models.SmallIntegerField('Jeunes femmes', default=0)
    non_binaire = models.SmallIntegerField('Personnes non binaires', default=0)

    # jour du mois maximum où il est encore possible de saisir des prestations du mois précédent
    max_jour = 5
    max_jour_re = 8

    class Meta:
        db_table = 'ser_prestationser'
        verbose_name = 'Prestation ASAP'
        verbose_name_plural = 'Prestations ASAP'

    def __str__(self):
        return f"{format_d_m_Y(self.date)} -  {self.auteur}: {format_duree(self.temps_total_prest())}"

    def temps_total_prest(self):
        return self.duree_suivi + self.duree_projet + self.duree_reseau + self.duree_admin + self.duree_prestation

    @classmethod
    def check_date_editable(cls, dt, user):
        """Contrôle si la prestation est modifiable en fonction de la date 'dt'."""
        max_delai = cls.max_jour_re if user.is_responsable_equipe else cls.max_jour
        today = date.today()
        prev_month = today.replace(day=1) - timedelta(days=1)
        return (

templates/ser/journal_change.html
{% extends 'base.html' %}

{% block content %}
<div class="row justify-content-center mb-5">
   <div class="col-lg-6 col-xs">
      <h1 class="page-header">ASAP - Journal de {{ person }}</h1>
      <form action="." method="post">{% csrf_token %}
         {{ form.non_field_errors }}
         <div class="row">
            <div class="col-md-6">{{ form.date.label_tag }}{{ form.date }} {{ form.date.errors }}</div>
            <div class="col-md-6">{{ form.duree.label_tag }}{{ form.duree }} {{ form.duree.errors }}</div>
            <div class="col-md-12 mt-4">{{ form.texte.label_tag }} {{ form.texte }} {{ form.text.errors }}</div>
         </div>
         {% if person|can_edit:user %}
         {% include 'actions.html' %}
         {% endif %}
      </form>
   </div>
</div>
{% endblock %}

templates/ser/journal_list.html
{% extends 'base.html' %}

{% block extra_javascript %}
<script>
$(document).ready(function() {
    $('a.read_more').click(toggle_read_more);
});
</script>
{% endblock %}

{% block content %}
<div class="row justify-content-center">
   <div class="col-lg-10 col-xs">
      <h1 class="page-header">ASAP - Journal de {{ person }}</h1>
      {% if person|can_edit:user %}
      <a href="{% url 'asap-journal-add' person.pk %}">
         <button type="button" class="btn btn-sm btn-success">
            <img class="me-1" src="{% static 'img/plus.svg' %}" width="11" >Ajouter une note</button>
      </a>
      {% endif %}
      <table class="table mt-3">
         <thead>
         <tr>
            <th>No</th>
            <th>Date</th>
            <th>Durée</th>
            <th>Texte</th>
            <th>Auteur</th>
         </tr>
         </thead>
      {% for note in notes %}
            <tr>
               <td width="5%">
                  <a href="{% url 'asap-journal-change' person.pk note.pk %}"># {{ forloop.counter }}</a>
               </td>
               <td width="15%">{{ note.date|date:"j N Y" }}</td>
               <td width="15%">{{ note.duree|strip_seconds }}</td>
               <td>{{ note.texte|truncate_with_more_and_default:40  }}</td>
               <td width="10%">{{ note.auteur.sigle }}</td>
            </tr>

      {% empty %}
         <tr><td colspan="4">Aucune note enregistrée</td></tr>
      {% endfor %}
      </table>
   </div>
</div>
{% endblock %}

templates/ser/person_change.html
{% extends 'base.html' %}

{% block content %}
<div class="row justify-content-center">
    <div class="col-lg-11 col-xs">
        <h1 class="page-header">ASAP - Bénéficiaire</h1>
        <form class="form form-person" action="." method="post">
            {% csrf_token %}
            <div class="row mb-3">
                <div class="col-lg-6">
                    {{ form.nom.label_tag }}{{ form.nom.errors }}{{ form.nom }}
                </div>
                <div class="col-lg-6">
                    {{ form.prenom.label_tag }}{{ form.prenom.errors }}{{ form.prenom }}
                    <small id="prenomHelp" class="form-text text-muted">Le prénom doit être unique!</small>
                </div>
            </div>
            <div class="row mb-3">
                <div class="col-lg-1">
                    {{ form.genre.label_tag }}{{ form.genre.errors }}{{ form.genre }}
                </div>
                <div class="col-lg-1">
                    {{ form.naissance_jour.label_tag }}{{ form.naissance_jour.errors }}{{ form.naissance_jour }}
                </div>
                <div class="col-lg-1">
                    {{ form.naissance_mois.label_tag }}{{ form.naissance_mois.errors }}{{ form.naissance_mois }}
                </div>
                <div class="col-lg-1">
                    {{ form.naissance_annee.label_tag }}{{ form.naissance_annee.errors }}{{ form.naissance_annee }}
                </div>
                <div class="col-lg-2">
                    {{ form.statut.label_tag }}{{ form.statut.errors }}{{ form.statut }}
                </div>
            </div>
            <div class="row mb-3">
                <div class="col-lg-6">
                    {{ form.telephone.label_tag }}{{ form.telephone.errors }}{{ form.telephone }}
                </div>
                <div class="col-lg-6">
                    {{ form.email.label_tag }}{{ form.email.errors }} {{ form.email }}
                </div>
            </div>
            <div class="row mb-3">
                <div class="col-lg-1">
                    {{ form.npa.label_tag }}{{ form.npa.errors }}{{ form.npa }}
               </div>
               <div class="col-lg-5">
                   {{ form.localite.label_tag }}{{ form.localite.errors }}{{ form.localite }}
               </div>
               <div class="col-lg-3">
                   {{ form.rue.label_tag }}{{ form.rue.errors }}{{ form.rue }}
               </div>
               <div class="col-lg-3">
                   {{ form.region.label_tag }}{{ form.region.errors }}{{ form.region }}
               </div>
            </div>

            <div class="row mb-3">
               <div class="col-lg-2">
                   {{ form.service_orienteur.label_tag }}{{ form.service_orienteur.errors }}{{ form.service_orienteur }}
               </div>
               <div class="col-lg-4">
                   {{ form.motif_demande.label_tag }}{{ form.motif_demande.errors }}{{ form.motif_demande }}
               </div>
                <div class="col-lg-6">
                    {{ form.educs.label_tag }}{{ form.educs.errors }}{{ form.educs }}
                </div>
            </div>
            <div class="row mb-3">
                <div class="col-lg-6">
                    {{ form.reseau_prof.label_tag }}{{ form.reseau_prof.errors }}{{ form.reseau_prof }}
                </div>
                <div class="col-lg-6">
                    {{ form.reseau_perso.label_tag }}{{ form.reseau_perso.errors }}{{ form.reseau_perso }}
                </div>
            </div>
            <div class="row mb-3">

                <div class="col-lg-12">
                    {{ form.remarque.label_tag }}{{ form.remarque.errors }}{{ form.remarque  }}
                </div>
            </div>
            {% if person %}
            <div class="row mt-3">
                <div class="col fw-bold">Documents:
                    {% if person|can_edit:user %}
                    <span>
                        <a href="{% url 'person-doc-upload' person.pk %}"
                           class="btn btn-sm btn-mini btn-primary"
                           role="button"
                           title="Ajouter un document">+</a>
                    </span>
                    {% endif %}
                </div>
                <div class="col-lg-10">
                    <div class="document-container">
                    {% for doc in documents %}
                        <div class="document">
                            {{ doc.date_creation|date:"d.m.Y" }} <a href="{{ doc.fichier.url }}">{{ doc.titre }}</a>
                            {% if person|can_edit:user %}
                            <span class="hoverimage">
                                <button type="submit" class="btn btn-xs confirm"
                                    formaction="{% url 'person-doc-delete' person.pk doc.pk %}"
                                    title="Supprimer ce document"
                                    data-confirm="Voulez-vous vraiment supprimer ce document ?">
                                    <img src="{% static 'admin/img/icon-deletelink.svg' %}">
                                </button>
                            </span>
                           {% endif %}
                        </div>
                    {% endfor %}
                    </div>
                </div>
            </div>
            {% endif %}
            {% if not form.instance.pk or form.instance|can_edit:user %}
                {% include "actions.html" %}
            {% endif %}
        </form>
    </div>
</div>
{% endblock %}

templates/ser/person_list.html
{% extends 'base.html' %}

{% block content %}
<div class="row justify-content-center">
   <div class="col-lg-10">
      <h1 class="page-header">ASAP - Bénéficiaires {{ view.titre }}</h1>
   </div>
</div>
<div class="row justify-content-center">
    <div class="col-lg-3">
        {% if perms.ser.change_ser %}
        <a href="{% url 'asap-person-add' %}">
            <button type="button" class="btn btn-sm btn-success">
                <img src="{% static 'img/plus.svg' %}" width="11"> Ajouter un-e bénéficiaire</button>
        </a>
        {% endif %}
    </div>
    <div class="col-lg-7 text-end">
        <form class="inline" method="get" action=".">
            <div class="select-container">
                {{ filter_form.letter.label_tag }} {{ filter_form.letter }}
                {{ filter_form.interv.label_tag }} {{ filter_form.interv }}
                {{ filter_form.region.label_tag }} {{ filter_form.region }}
                <button id="search-button" type="submit" title="Activer les filtres">
                    <img src="{% static 'admin/img/search.svg' %}">
                </button>
                <button id="reset-button" type="reset" title="Réinitialiser tous les filtres">
                    <img src="{% static 'img/filter_off.svg' %}">
                </button>
            </div>

        </form>
    </div>
</div>
<div class="row justify-content-center">
   <div class="col-lg-10">
      <table class="table table-responsive mt-5">
         <tr>
            <th>Bénéficiaire</th>
            <th>Région</th>
            <th>Réf. ASAP</th>
            <th>Journal</th>
         </tr>
      {% for person in persons %}
      <tr>
         <td><a href="{% url 'asap-person-change' person.pk %}">{{ person }}</a></td>
         <td>{{ person.get_region_display }}</td>
         <td>{{ person.get_educs }}</td>
         <td class="text-center">
            <a href="{% url 'asap-journal-list' person.pk %}">
               <img class="icon" src="{% static 'img/file-alt.svg' %}">
            </a>
         </td>
      </tr>
      {% endfor %}
      </table>
   </div>
</div>
{% endblock %}

templates/ser/place_change.html
{% extends 'base.html' %}

{% block content %}
<div class="row justify-content-center">
   <div class="col-lg-4 col-xs">
      <h1 class="page-header">ASAP - Sortie du BIP</h1>
      <form method="post">{% csrf_token %}
         {{ form.as_p }}
         {% include 'actions.html' %}
      </form>
   </div>
</div>
{% endblock %}

templates/ser/place_list.html
{% extends 'base.html' %}

{% block content %}
<div class="row justify-content-center">
   <div class="col-lg-5 col-xs">
      <h1 class="page-header">ASAP - Stationnements du BIP</h1>
      <a href="{% url 'asap-place-add' %}">
         <button type="button" class="btn btn-sm btn-success">
            <img src="{% static 'img/plus.svg' %}" width="11">Ajouter un stationnement</button>
      </a>
      <ul class="list-group mt-5">
      {% for place in object_list %}
         <li class="list-group-item"><a href="{% url 'asap-place-change' place.pk %}">{{ place }}</a></li>
      {% empty %}
         <li class="list-group-item">Aucun lieu enregistré</li>
      {% endfor %}
      </ul>
   </div>
</div>
{% endblock %}

templates/ser/prestation_change.html
{% extends 'base.html' %}

{% block content %}
<div class="row justify-content-center">
   <div class="col-lg-6 col-xs">
      <h1 class="page-header">Prestation générale</h1>
      <form class="form" method="post">{% csrf_token %}
         {{ form.non_fields_errors }}
         <div class="row">
            <div class="col-md-6">
               {{ form.date.label_tag }} {{ form.date }} {{ form.date.errors }}
            </div>
            <div class="col-md-6">
               {{ form.duree_prestation.label_tag }} {{ form.duree_prestation }} {{ form.duree_prestation.errors }}
            </div>
            <div class="col-md-12 mt-4">
               {{ form.motif.label_tag }} {{ form.motif }} {{ form.motif.errors }}
            </div>
         </div>
         {% include 'actions.html' %}
      </form>
   </div>
</div>
{% endblock %}

templates/ser/prestation_list.html
{% extends 'base.html' %}

{% block content %}
<div class="row justify-content-center mb-4">
    <div class="col-md-10">
        <h1 class="page-header">ASAP - Mes Prestations</h1>
        <div class="row mt-4 mb-4">
            <div class="col">
                <a href="{% url 'asap-prestation-add' %}" class="btn btn-sm btn-success">
                    <img src="{% static 'img/plus.svg' %}" width="11"> Ajouter une prestation générale
                </a>
                <a href="{% url 'asap-tshm-add' %}" class="btn btn-sm btn-success">
                    <img src="{% static 'img/plus.svg' %}" width="11"> Ajouter une sortie
                </a>
                <form class="d-inline" method="post" action="{% url 'asap-prestation-extra-add' 'pe' %}">
                    {% csrf_token %}
                    <button class="btn btn-sm btn-success"
                            title="Ajouter PE pour la semaine courante">Ajouter PE
                    </button>
                </form>
                <form class="d-inline" method="post" action="{% url 'asap-prestation-extra-add' 'bulle' %}">
                    {% csrf_token %}
                    <button class="btn btn-sm btn-success"
                            title="Ajouter BH pour la semaine courante">Ajouter BH
                    </button>
                </form>
            </div>
            <div class="col col-auto">
                <p class="lead">
                    {% if prev_month %}
                    <a class="btn btn-sm" href="?date={{ prev_month|date:'mY' }}">&lt;</a>
                    {% endif %}
                    {{ current_date.month|month_name }} {{ current_date.year }}
                    {% if next_month %}
                    <a class="btn btn-sm" href="?date={{ next_month|date:'mY' }}">&gt;</a>
                    {% endif %}
                </p>
            </div>
        </div>

        <div class="row gx-5">
            <div class="col-md-6">
                <div class="row justify-content-between border-bottom mb-3">
                    <div class="col lead ">Prestations générales</div>
                    <div class="col-auto lead text-end">Total: {{ tot_prest_gen|format_duree }} h.</div>
                </div>
                <table class="table">
                {% for prest in generales %}
                    <tr>
                        <td width="80%">
                            <a href="{% url 'asap-prestation-change' prest.pk %}">{{ prest.date }}</a>
                        </td>
                        <td class="text-end">{{ prest.duree_prestation|format_duree }}</td>
                    </tr>
                {% endfor %}
                </table>
            </div>
            <div class="col-md-6">
                 <div class="row justify-content-between border-bottom mb-3">
                    <div class="col lead ">Prestations indiv. et d'accomp.</div>
                    <div class="col-auto lead text-end">Total: {{ tot_prest_ind|format_duree }} h.</div>
                </div>
                <table class="table">
                    {% for item in personnes %}
                    <tr>
                        <td width="80%">
                           <a href="{% url 'asap-journal-list' item.person.pk %}">{{ item.person.nom_prenom }}</a>
                        </td>
                    <td class="text-end">{{ item.total|format_duree }}</td>
                    </tr>
                    {% endfor %}
                    {% for sortie in sorties %}
                    <tr>
                        <td><a href="{% url 'asap-tshm-change' sortie.pk %}">Sortie du {{ sortie.date}}</a></td>
                        <td class="text-end">{{ sortie.duree_prestation|format_duree }}</td>
                    </tr>
                    {% endfor %}
                    {% for prest in equipe %}
                    <tr>
                        <td><a href="{% url 'asap-prestation-change' prest.pk %}">
                            {{ prest.get_motif_display }} - {{ prest.date }}</a></td>
                        <td class="text-end">{{ prest.duree_prestation|format_duree }}</td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}